# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp_rtk board-specific Kconfig settings.

CONFIG_BOARD_OJAL=y

CONFIG_PLATFORM_EC_SWITCH=y
CONFIG_PLATFORM_EC_HOSTCMD=y

CONFIG_PWM=y
CONFIG_PLATFORM_EC_I2C=y
CONFIG_NAMED_ADC_CHANNELS=y
CONFIG_PLATFORM_EC_CONSOLE_CMD_CHARGEN=y

# CBI configuration
CONFIG_PLATFORM_EC_CBI=y
CONFIG_PLATFORM_EC_CBI_FLASH=y
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y

# Disable Power Delivery Function
CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=n
CONFIG_PLATFORM_EC_USB_PD_TCPMV2=n
CONFIG_PLATFORM_EC_USBC_SS_MUX=n
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_USB_MUX_TASK=n
CONFIG_PLATFORM_EC_USB_PD_REQUIRE_AP_MODE_ENTRY=n
CONFIG_PLATFORM_EC_USB_PD_TBT_COMPAT_MODE=n
CONFIG_PLATFORM_EC_USB_PD_USB4=n
CONFIG_PLATFORM_EC_USB_PD_DP_MODE=y
CONFIG_PLATFORM_EC_USB_PD_HOST_CMD=y
CONFIG_PLATFORM_EC_USB_PD_REV30=y
#CONFIG_USBC_PDC_DRIVEN_CCD=y
CONFIG_PLATFORM_EC_USBC=y

# PDC
CONFIG_PLATFORM_EC_USB_PD_CONTROLLER=y
CONFIG_PDC_RUNTIME_PORT_CONFIG=n

# Charger
CONFIG_PLATFORM_EC_CHARGER_RAA489110=n
CONFIG_PLATFORM_EC_CHARGER_ISL9238C=y
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR=10
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR_AC=20
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_PDC=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=n

# Battery support
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=n
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=y
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_FUEL_GAUGE=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y

# Buttons
CONFIG_PLATFORM_EC_POWER_BUTTON=y
CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# Lid Switch
CONFIG_PLATFORM_EC_LID_SWITCH=y

# Keyboard support
CONFIG_INPUT=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_CROS_EC_KEYBOARD_INPUT=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_PLATFORM_EC_KEYBOARD=y
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y

# AP Power Sequencing
CONFIG_AP=y
CONFIG_AP_X86_INTEL_MTL=y
CONFIG_AP_PWRSEQ_DRIVER=n
CONFIG_X86_NON_DSX_PWRSEQ_MTL=y

# eSPI
CONFIG_ESPI=y
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S3=y
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S4=y
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S5=y
CONFIG_ESPI_VWIRE_VALID_BIT_CHECK=n
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y

# Postcode
CONFIG_PLATFORM_EC_PORT80=y
CONFIG_PLATFORM_EC_PORT80_4_BYTE=y

# ULPM
CONFIG_SOC_RTS5912_ULPM=y
CONFIG_POWEROFF=y
