/*
 * Copyright 2021 Google LLC.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef DT_BINDINGS_EC_MKBP_EVENT_DEFINES_H_
#define DT_BINDINGS_EC_MKBP_EVENT_DEFINES_H_

#ifndef BIT
#define BIT(n) (1U << n)
#endif

/* Keyboard matrix changed. The event data is the new matrix state. */
#define EC_MKBP_EVENT_KEY_MATRIX	BIT(0)

/* New host event. The event data is 4 bytes of host event flags. */
#define EC_MKBP_EVENT_HOST_EVENT	BIT(1)

/* New Sensor FIFO data. The event data is fifo_info structure. */
#define EC_MKBP_EVENT_SENSOR_FIFO	BIT(2)

/* The state of the non-matrixed buttons have changed. */
#define EC_MKBP_EVENT_BUTTON		BIT(3)

/* The state of the switches have changed. */
#define EC_MKBP_EVENT_SWITCH		BIT(4)

/* New Fingerprint sensor event) the event data is fp_events bitmap. */
#define EC_MKBP_EVENT_FINGERPRINT	BIT(5)

/*
 * Sysrq event: send emulated sysrq. The event data is sysrq)
 * corresponding to the key to be pressed.
 */
#define EC_MKBP_EVENT_SYSRQ		BIT(6)

/*
 * New 64-bit host event.
 * The event data is 8 bytes of host event flags.
 */
#define EC_MKBP_EVENT_HOST_EVENT64	BIT(7)

/* Notify the AP that something happened on CEC */
#define EC_MKBP_EVENT_CEC_EVENT		BIT(8)

/* Send an incoming CEC message to the AP */
#define EC_MKBP_EVENT_CEC_MESSAGE	BIT(9)

/* We have entered DisplayPort Alternate Mode on a Type-C port. */
#define EC_MKBP_EVENT_DP_ALT_MODE_ENTERED	BIT(10)

/* New online calibration values are available. */
#define EC_MKBP_EVENT_ONLINE_CALIBRATION	BIT(11)

/* Peripheral device charger event */
#define EC_MKBP_EVENT_PCHG		BIT(12)


/*
 * Host event codes. ACPI query EC command uses code 0 to mean "no event
 * pending".  We explicitly specify each value in the enum listing so they won't
 * change if we delete/insert an item or rearrange the list (it needs to be
 * stable across platforms) not just within a single compiled instance).
 */

#define EC_HOST_EVENT_NONE		BIT(0)
#define EC_HOST_EVENT_LID_CLOSED	BIT(1)
#define EC_HOST_EVENT_LID_OPEN		BIT(2)
#define EC_HOST_EVENT_POWER_BUTTON	BIT(3)
#define EC_HOST_EVENT_AC_CONNECTED	BIT(4)
#define EC_HOST_EVENT_AC_DISCONNECTED	BIT(5)
#define EC_HOST_EVENT_BATTERY_LOW	BIT(6)
#define EC_HOST_EVENT_BATTERY_CRITICAL	BIT(7)
#define EC_HOST_EVENT_BATTERY		BIT(8)
#define EC_HOST_EVENT_THERMAL_THRESHOLD	BIT(9)
/* Event generated by a device attached to the EC */
#define EC_HOST_EVENT_DEVICE		BIT(10)
#define EC_HOST_EVENT_THERMAL		BIT(11)
#define EC_HOST_EVENT_USB_CHARGER	BIT(12)
#define EC_HOST_EVENT_KEY_PRESSED	BIT(13)
/*
 * EC has finished initializing the host interface.  The host can check
 * for this event following sending a EC_CMD_REBOOT_EC command to
 * determine when the EC is ready to accept subsequent commands.
 */
#define EC_HOST_EVENT_INTERFACE_READY	BIT(14)
/* Keyboard recovery combo has been pressed */
#define EC_HOST_EVENT_KEYBOARD_RECOVERY	BIT(15)

/* Shutdown due to thermal overload */
#define EC_HOST_EVENT_THERMAL_SHUTDOWN	BIT(16)
/* Shutdown due to battery level too low */
#define EC_HOST_EVENT_BATTERY_SHUTDOWN	BIT(17)

/* Suggest that the AP throttle itself */
#define EC_HOST_EVENT_THROTTLE_START	BIT(18)
/* Suggest that the AP resume normal speed */
#define EC_HOST_EVENT_THROTTLE_STOP	BIT(19)

/* Hang detect logic detected a hang and host event timeout expired */
#define EC_HOST_EVENT_HANG_DETECT	BIT(20)
/* Hang detect logic detected a hang and warm rebooted the AP */
#define EC_HOST_EVENT_HANG_REBOOT	BIT(21)

/* PD MCU triggering host event */
#define EC_HOST_EVENT_PD_MCU		BIT(22)

/* Battery Status flags have changed */
#define EC_HOST_EVENT_BATTERY_STATUS	BIT(23)

/* EC encountered a panic) triggering a reset */
#define EC_HOST_EVENT_PANIC		BIT(24)

/* Keyboard fastboot combo has been pressed */
#define EC_HOST_EVENT_KEYBOARD_FASTBOOT	BIT(25)

/* EC RTC event occurred */
#define EC_HOST_EVENT_RTC		BIT(26)

/* Emulate MKBP event */
#define EC_HOST_EVENT_MKBP		BIT(27)

/* EC desires to change state of host-controlled USB mux */
#define EC_HOST_EVENT_USB_MUX		BIT(28)
/*
 * The device has changed "modes". This can be one of the following:
 *
 * - TABLET/LAPTOP mode
 * - detachable base attach/detach event
 */
#define EC_HOST_EVENT_MODE_CHANGE	BIT(29)

/* Keyboard recovery combo with hardware reinitialization */
#define EC_HOST_EVENT_KEYBOARD_RECOVERY_HW_REINIT	BIT(30)

/* WoV */
#define EC_HOST_EVENT_WOV		BIT(31)

/*
 * The high bit of the event mask is not used as a host event code.  If
 * it reads back as set) then the entire event mask should be
 * considered invalid by the host.  This can happen when reading the
 * raw event status via EC_MEMMAP_HOST_EVENTS but the LPC interface is
 * not initialized on the EC) or improperly configured on the host.
 */
#define EC_HOST_EVENT_INVALID		BIT(32)

#endif /* DT_BINDINGS_EC_MKBP_EVENT_DEFINES_H_ */

