# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# quartz board-specific Kconfig settings.

CONFIG_BOARD_QUARTZ=y

# Fan
CONFIG_PLATFORM_EC_NUM_FANS=2
CONFIG_PLATFORM_EC_CUSTOM_FAN_CONTROL=y

# Added as temporary solution to b/437979589
# Issue ec command `apshutdown` before programming EC or AP
CONFIG_PLATFORM_EC_BRINGUP=y

# MKBP
CONFIG_PLATFORM_EC_MKBP_EVENT=y
CONFIG_PLATFORM_EC_MKBP_INPUT_DEVICES=y
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD=y
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_MKBP=y
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y
CONFIG_PLATFORM_EC_KEYBOARD_STRICT_DEBOUNCE=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
