# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Crystaldrift reference-board-specific Kconfig settings.
CONFIG_BOARD_CRYSTALDRIFT=y

# CBI WP pin present
CONFIG_PLATFORM_EC_EEPROM_CBI_WP=y

# Crystaldrfit is capable of sinking 100W
CONFIG_PLATFORM_EC_PD_MAX_POWER_MW=100000
CONFIG_PLATFORM_EC_PD_MAX_CURRENT_MA=5000
CONFIG_PLATFORM_EC_PD_MAX_VOLTAGE_MV=20000

# Enable alternative charger chip
CONFIG_PLATFORM_EC_CHARGER_RUNTIME_CONFIG=y
CONFIG_PLATFORM_EC_CHARGER_ISL9238C=y

# Battery
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=y
# Motion sense
CONFIG_PLATFORM_EC_MOTIONSENSE=n
CONFIG_PLATFORM_EC_ACCEL_FIFO=n
CONFIG_PLATFORM_EC_ACCEL_SPOOF_MODE=n
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=n
CONFIG_PLATFORM_EC_LID_ANGLE=n
CONFIG_PLATFORM_EC_LID_ANGLE_UPDATE=n
CONFIG_PLATFORM_EC_SENSOR_TIGHT_TIMESTAMPS=n
CONFIG_PLATFORM_EC_TABLET_MODE=n
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=n
CONFIG_PLATFORM_EC_TABLET_MODE=n
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=n
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=n

# Sensor Drivers
CONFIG_PLATFORM_EC_ACCEL_BMA4XX=n
CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=n
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=n
