/* Copyright 2023 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#include "common.h"
#include "openssl/bn.h"
#include "openssl/ec.h"
#include "openssl/mem.h"
#include "openssl/obj_mac.h"
#include "openssl/rand.h"
#include "test_util.h"
#include "util.h"

test_static enum ec_error_list test_rand(void)
{
	uint8_t buf1[256], buf2[256];

	RAND_bytes(buf1, sizeof(buf1));
	RAND_bytes(buf2, sizeof(buf2));

	uint8_t expect_not_zero_1 = 0;
	uint8_t expect_not_zero_2 = 0;
	uint8_t expect_not_zero_3 = 0;

	/* The TRNG result of buf1 & buf2 should not be zero, and should not be
	 * the same. */
	for (int i = 0; i < 256; i++) {
		expect_not_zero_1 |= buf1[i];
		expect_not_zero_2 |= buf2[i];
		expect_not_zero_3 |= buf1[i] ^ buf2[i];
	}

	TEST_NE(expect_not_zero_1, 0, "%d");
	TEST_NE(expect_not_zero_2, 0, "%d");
	TEST_NE(expect_not_zero_3, 0, "%d");

	return EC_SUCCESS;
}

test_static enum ec_error_list test_ecc_keygen(void)
{
	bssl::UniquePtr<EC_KEY> key1(
		EC_KEY_new_by_curve_name(NID_X9_62_prime256v1));

	TEST_NE(key1.get(), nullptr, "%p");

	TEST_EQ(EC_KEY_generate_key(key1.get()), 1, "%d");

	/* The key generated by the TRNG should be valid.*/
	TEST_EQ(EC_KEY_check_key(key1.get()), 1, "%d");

	bssl::UniquePtr<EC_KEY> key2(
		EC_KEY_new_by_curve_name(NID_X9_62_prime256v1));

	TEST_NE(key2.get(), nullptr, "%p");

	TEST_EQ(EC_KEY_generate_key(key2.get()), 1, "%d");

	/* The key generated by the TRNG should be valid. */
	TEST_EQ(EC_KEY_check_key(key2.get()), 1, "%d");

	const BIGNUM *priv1 = EC_KEY_get0_private_key(key1.get());
	const BIGNUM *priv2 = EC_KEY_get0_private_key(key2.get());

	/* The keys generated by the TRNG should not be the same. */
	TEST_NE(BN_cmp(priv1, priv2), 0, "%d");

	/* The keys generated by the TRNG should not be zero. */
	TEST_EQ(BN_is_zero(priv1), 0, "%d");
	TEST_EQ(BN_is_zero(priv2), 0, "%d");

	return EC_SUCCESS;
}

extern "C" void run_test(int argc, const char **argv)
{
	RUN_TEST(test_rand);
	RUN_TEST(test_ecc_keygen);
	test_print_result();
}
