/* Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 *
 * Context switching
 */

#include "config.h"

.text

.global __switchto
__switchto:
	/* TODO(crosbug.com/p/23574): IMPLEMENT ME ! */
	ret $lp

.global __task_start
__task_start:
	/* TODO(crosbug.com/p/23574): IMPLEMENT ME ! */
	ret $lp

