# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_REALTEKFP=y

# Power Management
CONFIG_PM=n
CONFIG_PM_DEVICE=n

# Peripherials
CONFIG_BBRAM=n

# Hwinfo
CONFIG_HWINFO=y

# Priorities
CONFIG_PLATFORM_EC_SYSTEM_PRE_INIT_PRIORITY=72

# Host Commands
CONFIG_EC_HOST_CMD_INITIALIZE_AT_BOOT=y

# Enable USB for HC
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# Config to full speed since it is not support in usb host cmd yet
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
CONFIG_USBD_MAX_SPEED_FULL=y
CONFIG_UDC_BUF_POOL_SIZE=3072
CONFIG_USB_DEVICE_MAX_POWER=250

CONFIG_USB_DEVICE_MANUFACTURER="Google"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="0"
# CONFIG_USB_DEVICE_SN_HWINFO=y

CONFIG_FLASH_SHELL=n
