# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_REALTEKFP=y

# Power Management
CONFIG_PM=n
CONFIG_PM_DEVICE=n

# Peripherials
CONFIG_BBRAM=n

# Hwinfo
CONFIG_HWINFO=y

# Priorities
CONFIG_PLATFORM_EC_SYSTEM_PRE_INIT_PRIORITY=72

# Host Commands
CONFIG_EC_HOST_CMD_INITIALIZE_AT_BOOT=n

CONFIG_FLASH_SHELL=n
CONFIG_FLASH_EX_OP_ENABLED=y
