# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# atriarvp-rtk board-specific Kconfig settings.

CONFIG_BOARD_ATRIARVP_RTK=y

# This is appropriate for an RVP
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# eSPI
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
# FIXME: This config is not defined for RTS5912 upstream; how does removing this
# break the ESPI shim?
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_ISL9238C=y
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR=10
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR_AC=20
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_PDC=y

# Battery support
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=y
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_FUEL_GAUGE=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y
