# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y

CONFIG_BOARD_DRAWCIA_RISCV=y
CONFIG_AP=n
CONFIG_PLATFORM_EC_POWERSEQ=n
CONFIG_PLATFORM_EC_POWERSEQ_HOST_SLEEP=n

# Bring up options
CONFIG_KERNEL_SHELL=y
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Host Commands
CONFIG_PLATFORM_EC_HOSTCMD=y
CONFIG_PLATFORM_EC_CONSOLE_CMD_SYSINFO=y
CONFIG_PLATFORM_EC_HOST_COMMAND_STATUS=y

# VBoot without EFS2
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
CONFIG_PLATFORM_EC_VBOOT_HASH=y

# Turn off config that is set in the default config
# TODO(b/209324248): Fix the default IT8xxx2 configuration.
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_CROS_KB_RAW_ITE=n
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_MKBP=n
CONFIG_PLATFORM_EC_KEYBOARD_COL2_INVERTED=n
CONFIG_PLATFORM_EC_MKBP_EVENT=n
CONFIG_PLATFORM_EC_MKBP_INPUT_DEVICES=n
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
