# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_DIRKS=y

# No sub-board supported
CONFIG_DIRKS_SUB_BOARD=n

# No fan supported, and tach is default-enabled
CONFIG_TACH_IT8XXX2=n

# USB Type A Features
CONFIG_PLATFORM_EC_USB_PORT_POWER_DUMB=y

# buttons
CONFIG_PLATFORM_EC_DEDICATED_RECOVERY_BUTTON=y
CONFIG_PLATFORM_EC_DEDICATED_RECOVERY_BUTTON_ACTIVE_HIGH=y

# Required to make it build
CONFIG_PLATFORM_EC_HIBERNATE_PSL=n

# HDMI CEC
CONFIG_PLATFORM_EC_CEC=y
CONFIG_PLATFORM_EC_CEC_IT83XX=y
CONFIG_PLATFORM_EC_CEC_BITBANG=y
