# -*- makefile -*-
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Board specific files build

# the IC is STmicro STM32F072RBT6
CHIP:=stm32
CHIP_FAMILY:=stm32f0
CHIP_VARIANT:=stm32f07x

board-y=board.o

# This list is generated by removing the relevant
# CONFIG defines from board.h and printing the
# +$(info $(ro-objs)) variable from ec/Makefile
custom-ro_objs-y = \
	board/servo_v4/board.o \
	chip/stm32/clock-f.o \
	chip/stm32/clock-stm32f0.o \
	chip/stm32/dma.o \
	chip/stm32/flash-f.o \
	chip/stm32/flash-stm32f0.o \
	chip/stm32/gpio-stm32f0.o \
	chip/stm32/gpio.o \
	chip/stm32/hwtimer32.o \
	chip/stm32/i2c-stm32f0.o \
	chip/stm32/jtag-stm32f0.o \
	chip/stm32/system.o \
	chip/stm32/uart.o \
	chip/stm32/usb-stm32f0.o \
	chip/stm32/usb-stream.o \
	chip/stm32/usb.o \
	chip/stm32/usb_console.o \
	chip/stm32/usb_endpoints.o \
	chip/stm32/watchdog.o \
	common/clz.o \
	common/console.o \
	common/console_output.o \
	common/flash.o \
	common/fmap.o \
	common/gpio.o \
	common/gpio_commands.o \
	common/hooks.o \
	common/i2c.o \
	common/main.o \
	common/memory_commands.o \
	common/panic_output.o \
	common/printf.o \
	common/queue.o \
	common/queue_policies.o \
	common/shared_mem.o \
	common/system.o \
	common/timer.o \
	common/uart_buffering.o \
	common/update_fw.o \
	common/usb_update.o \
	common/util.o \
	common/version.o \
	core/cortex-m0/cpu.o \
	core/cortex-m0/div.o \
	core/cortex-m0/init.o \
	core/cortex-m0/ldivmod.o \
	core/cortex-m0/lmul.o \
	core/cortex-m0/panic.o \
	core/cortex-m0/switch.o \
	core/cortex-m0/task.o \
	core/cortex-m0/thumb_case.o \
	core/cortex-m0/uldivmod.o \
	core/cortex-m0/watchdog.o

