# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_ROACH=y

# placeholder, we don't have a real touchpad fw yet.
# CONFIG_PLATFORM_EC_TOUCHPAD_VIRTUAL_SIZE=65536
# CONFIG_PLATFORM_EC_TOUCHPAD_VIRTUAL_OFF=65536

CONFIG_PLATFORM_EC_ONE_WIRE_UART_KEYBOARD=n

CONFIG_PLATFORM_EC_TOUCHPAD_ELAN=n

# USB
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_MANUFACTURER="Google LLC"
CONFIG_USB_DEVICE_PRODUCT="Roach"
CONFIG_USB_DEVICE_SN="0"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0x5999
CONFIG_USB_DEVICE_HID=y
CONFIG_USB_SELF_POWERED=n

CONFIG_USB_HID_BOOT_PROTOCOL=y
CONFIG_HID_INTERRUPT_EP_MPS=64
CONFIG_USB_HID_DEVICE_COUNT=1

CONFIG_USB_DC_HID_KEYBOARD=y
CONFIG_USB_DC_HID_TOUCHPAD=n

CONFIG_PLATFORM_EC_USB_UPDATE=n


CONFIG_PLATFORM_EC_TOUCHPAD_HASH_FW=n
