# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_ROACH=y

CONFIG_PLATFORM_EC_TOUCHPAD_ELAN=y
CONFIG_PLATFORM_EC_RWSIG=n
CONFIG_PLATFORM_EC_RSA_EXPONENT_3=n

CONFIG_PLATFORM_EC_ONE_WIRE_UART_KEYBOARD=n

## For USB DC stack
#CONFIG_USB_DEVICE_STACK=y
#CONFIG_USB_DEVICE_MANUFACTURER="Google"
#CONFIG_USB_DEVICE_PRODUCT="Roach"
#CONFIG_USB_DEVICE_SN="0"
#CONFIG_USB_DEVICE_VID=0x1801
#CONFIG_USB_DEVICE_PID=0x5999
#CONFIG_USB_DEVICE_HID=y
#CONFIG_USB_SELF_POWERED=n
#CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
#CONFIG_USB_HID_BOOT_PROTOCOL=y
#CONFIG_HID_INTERRUPT_EP_MPS=64
#CONFIG_USB_HID_DEVICE_COUNT=2
#CONFIG_USB_DC_HID_KEYBOARD=y
#CONFIG_USB_DC_HID_VIVALDI=y
#CONFIG_USB_DC_HID_TOUCHPAD=y

## For USBD stack
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_USBD_HID_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USBD_HID_SUPPORT=y
CONFIG_USBD_HID_PRODUCT="Roach"
CONFIG_USBD_HID_PID=0x5999
CONFIG_USBD_HID_SN="0"
CONFIG_USBD_HID_KEYBOARD=y
CONFIG_USBD_HID_VIVALDI=y
CONFIG_USBD_HID_TOUCHPAD=y


