# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

image: sjg20/bionic-20200526-12feb21

# You can update that image using this repo:
#   https://gitlab.com/zephyr-ec/gitlab-ci-runner/-/tree/main

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/


# The directory structure is:
#
# /zephyr                    ZEPHYR_DIR
# /zephyr/main/v2.4
# /zephyr/cmsis/v2.4
# /zephyr/hal_stm32/v2.4
# /builds/zephyr-ec/ec       EC_DIR
before_script:
  - pwd
  - ls -l /zephyr
  - python3 -V  # Print out python version for debugging
  - python3 -m pip install zephyr/zmake --user
  - export BUILD_DIR=build
  - export EC_DIR=`pwd`
  - export ZEPHYR_DIR=/zephyr
  - export PATH=$PATH:~/.local/bin
  - git -C $ZEPHYR_DIR/main/v2.4 fetch
  - git -C $ZEPHYR_DIR/main/v2.4 checkout origin/chromeos-v2.4
  - git -C $ZEPHYR_DIR/main/v2.4 log --oneline -n5
  - git -C $ZEPHYR_DIR/cmsis/v2.4 fetch
  - git -C $ZEPHYR_DIR/cmsis/v2.4 checkout origin/chromeos-v2.4
  - git -C $ZEPHYR_DIR/cmsis/v2.4 log --oneline -n5

# Not used yet
# git -C $ZEPHYR_DIR/hal_stm32/v2.4 fetch
# git -C $ZEPHYR_DIR/hal_stm32/v2.4 log --oneline -n5

test:
  script:
    echo "It works"

run:
  script:
    - pwd
    - zmake -l DEBUG configure -B ${BUILD_DIR}/vol -t zephyr
      --zephyr-base $ZEPHYR_DIR/main/v2.4 --modules-base $ZEPHYR_DIR
      zephyr/projects/volteer
    - zmake -l DEBUG build ${BUILD_DIR}/vol
    - ls ${BUILD_DIR}/vol ${BUILD_DIR}/vol/output
  artifacts:
    paths:
      - build/vol/output/*
    expire_in: 1 week
