# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: sjg20/bionic-20200526-28jan2021

# You can update that image using this repo:
#   https://gitlab.com/zephyr-ec/gitlab-ci-runner/-/tree/master

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V  # Print out python version for debugging
  - python3 -m pip install -e zephyr/zmake --user
  - export BUILD_DIR=/tmp/z
  - export PATH=$PATH:~/.local/bin

test:
  script:
    echo "It works"

run:
  script:
    - zmake configure -B ${BUILD_DIR}/vol zephyr/projects/volteer
    - zmake build ${BUILD_DIR}/vol
  artifacts:
    paths:
      - ${BUILD_DIR}/vol

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
