# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelot_nuvoton board-specific Kconfig settings.

CONFIG_BOARD_OCELOT_NUVOTON=y


CONFIG_PLATFORM_EC_I2C=y

# Enable AP over eSPI
CONFIG_ESPI=y

# Power Sequencing
CONFIG_AP_X86_INTEL_MTL=y
CONFIG_X86_NON_DSX_PWRSEQ_MTL=y
CONFIG_ESPI_VWIRE_VALID_BIT_CHECK=n

CONFIG_AP=y


CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S3=y
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S4=y
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S5=y

CONFIG_PLATFORM_EC_POWER_BUTTON=y
CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y

CONFIG_PLATFORM_EC_SWITCH=y

CONFIG_PLATFORM_EC_LID_SWITCH=y

CONFIG_INPUT=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y

CONFIG_PLATFORM_EC_USB_PD_CONTROLLER=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_RAA489110=y
CONFIG_PLATFORM_EC_CHARGER_DISCHARGE_ON_AC=y
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR=5
CONFIG_PLATFORM_EC_CHARGER_SENSE_RESISTOR_AC=10
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=y

CONFIG_PLATFORM_EC_USB_PD_MAX_POWER_MW=100000
CONFIG_PLATFORM_EC_USB_PD_MAX_CURRENT_MA=5000

# Battery
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_FUEL_GAUGE=y
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y


CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON_WITH_BATT=15000
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON=65000
CONFIG_PLATFORM_EC_CHARGER_MIN_INPUT_CURRENT_LIMIT=512

#IOEX present on main board
CONFIG_GPIO_PCA95XX_INIT_PRIORITY=50
