# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Pujjocento reference-board-specific Kconfig settings.
CONFIG_BOARD_PUJJOCENTO=y

# CBI
CONFIG_PLATFORM_EC_CBI=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
CONFIG_PLATFORM_EC_KEYBOARD_COLS=18
CONFIG_PLATFORM_EC_KBLIGHT_ENABLE_PIN=y

# Battery
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y
CONFIG_PLATFORM_EC_BATTERY_PRESENT_NONE=n
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=y

#Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

#Hibernate
CONFIG_PLATFORM_EC_HIBERNATE_PSL=y

# Charger
CONFIG_PLATFORM_EC_CHARGER_ILIM_PIN_DISABLED=y

CONFIG_PDC_RUNTIME_PORT_CONFIG=n
