# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y

# SoC configuration
CONFIG_AP=n

# ADC
CONFIG_ADC=y
CONFIG_ADC_SHELL=n

# I2C master
CONFIG_I2C=y

# PWM
CONFIG_PWM=n
CONFIG_PLATFORM_EC_PWM=n

CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
CONFIG_PLATFORM_EC_VBOOT=n
CONFIG_PLATFORM_EC_VBOOT_HASH=n

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD=n

# Host command
CONFIG_PLATFORM_EC_HOSTCMD=y

# Power button
CONFIG_PLATFORM_EC_POWER_BUTTON=y
CONFIG_HAS_TASK_POWERBTN=n

# Lid switch
CONFIG_PLATFORM_EC_LID_SWITCH=y

# Board version
CONFIG_PLATFORM_EC_BOARD_VERSION=y

# Flash
CONFIG_PLATFORM_EC_FLASH=y

CONFIG_LOG=y

