# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_GROGU=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_COL2_INVERTED=n
CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y
<<<<<<< HEAD
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=n
CONFIG_PLATFORM_EC_KEYBOARD_STRAUSS=y
