# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_KRABBY=y

# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD_PWRBTN_ASSERTS_KSI2=y

# HOSTCMD
CONFIG_EC_HOST_CMD=y
CONFIG_EC_HOST_CMD_PERIPH=y
CONFIG_EC_HOST_CMD_PERIPH_SHI=y
CONFIG_PM_DEVICE_RUNTIME=y
