/* Copyright 2016 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#include "fuses.h"
#include "registers.h"

int fuses_are_locked(void)
{
	return ((GR_FUSE(BNK0_INTG_LOCK) == FUSE_ENABLED) ||
		(GR_FUSE(BNK1_INTG_LOCK) == FUSE_ENABLED) ||
		(GR_FUSE(BNK2_INTG_LOCK) == FUSE_ENABLED) ||
		(GR_FUSE(BNK3_INTG_LOCK) == FUSE_ENABLED) ||
		(GR_FUSE(BNK4_INTG_LOCK) == FUSE_ENABLED));
}

void init_fuses(void)
{
	GWRITE(FUSE, PROG_BNK0_INTG_CHKSUM, GR_FUSE(BNK0_INTG_CHKSUM));
	GWRITE(FUSE, PROG_BNK0_INTG_LOCK, GR_FUSE(BNK0_INTG_LOCK));

	GWRITE(FUSE, PROG_DS_GRP0, GR_FUSE(DS_GRP0));
	GWRITE(FUSE, PROG_DS_GRP1, GR_FUSE(DS_GRP1));
	GWRITE(FUSE, PROG_DS_GRP2, GR_FUSE(DS_GRP2));

	GWRITE(FUSE, PROG_DEV_ID0, GR_FUSE(DEV_ID0));
	GWRITE(FUSE, PROG_DEV_ID1, GR_FUSE(DEV_ID1));

	GWRITE(FUSE, PROG_BNK1_INTG_CHKSUM, GR_FUSE(BNK1_INTG_CHKSUM));
	GWRITE(FUSE, PROG_BNK1_INTG_LOCK, GR_FUSE(BNK1_INTG_LOCK));

	GWRITE(FUSE, PROG_LB0_POST_OVRD, GR_FUSE(LB0_POST_OVRD));
	GWRITE(FUSE, PROG_LB0_POST_PATCNT, GR_FUSE(LB0_POST_PATCNT));
	GWRITE(FUSE, PROG_LB0_POST_WARMUP_OVRD,
		GR_FUSE(LB0_POST_WARMUP_OVRD));
	GWRITE(FUSE, PROG_LB0_POST_WARMUP_CNT, GR_FUSE(LB0_POST_WARMUP_CNT));

	GWRITE(FUSE, PROG_LB1_POST_OVRD, GR_FUSE(LB1_POST_OVRD));
	GWRITE(FUSE, PROG_LB1_POST_PATCNT, GR_FUSE(LB1_POST_PATCNT));
	GWRITE(FUSE, PROG_LB1_POST_WARMUP_OVRD,
		GR_FUSE(LB1_POST_WARMUP_OVRD));
	GWRITE(FUSE, PROG_LB1_POST_WARMUP_CNT, GR_FUSE(LB1_POST_WARMUP_CNT));

	GWRITE(FUSE, PROG_LB2_POST_OVRD, GR_FUSE(LB2_POST_OVRD));
	GWRITE(FUSE, PROG_LB2_POST_PATCNT, GR_FUSE(LB2_POST_PATCNT));
	GWRITE(FUSE, PROG_LB2_POST_WARMUP_OVRD,
		GR_FUSE(LB2_POST_WARMUP_OVRD));
	GWRITE(FUSE, PROG_LB2_POST_WARMUP_CNT, GR_FUSE(LB2_POST_WARMUP_CNT));

	GWRITE(FUSE, PROG_LB3_POST_OVRD, GR_FUSE(LB3_POST_OVRD));
	GWRITE(FUSE, PROG_LB3_POST_PATCNT, GR_FUSE(LB3_POST_PATCNT));
	GWRITE(FUSE, PROG_LB3_POST_WARMUP_OVRD,
		GR_FUSE(LB3_POST_WARMUP_OVRD));
	GWRITE(FUSE, PROG_LB3_POST_WARMUP_CNT, GR_FUSE(LB3_POST_WARMUP_CNT));

	GWRITE(FUSE, PROG_LB4_POST_OVRD, GR_FUSE(LB4_POST_OVRD));
	GWRITE(FUSE, PROG_LB4_POST_PATCNT, GR_FUSE(LB4_POST_PATCNT));
	GWRITE(FUSE, PROG_LB4_POST_WARMUP_OVRD,
		GR_FUSE(LB4_POST_WARMUP_OVRD));
	GWRITE(FUSE, PROG_LB4_POST_WARMUP_CNT, GR_FUSE(LB4_POST_WARMUP_CNT));

	GWRITE(FUSE, PROG_MBIST_POST_SEQ, GR_FUSE(MBIST_POST_SEQ));

	GWRITE(FUSE, PROG_LBIST_POST_SEQ, GR_FUSE(LBIST_POST_SEQ));
	GWRITE(FUSE, PROG_LBIST_VIA_TAP_DIS, GR_FUSE(LBIST_VIA_TAP_DIS));

	GWRITE(FUSE, PROG_MBIST_VIA_TAP_DIS, GR_FUSE(MBIST_VIA_TAP_DIS));
	GWRITE(FUSE, PROG_MBIST_BOOTROM_MISR_EN, 0);
	GWRITE(FUSE, PROG_MBIST_BOOTROM_MISR, 0);

	GWRITE(FUSE, PROG_TAP_DISABLE, GR_FUSE(TAP_DISABLE));

	GWRITE(FUSE, PROG_RNGBIST_AR_EN, GR_FUSE(RNGBIST_AR_EN));

	GWRITE(FUSE, PROG_TESTMODE_KEYS_EN, GR_FUSE(TESTMODE_KEYS_EN));

	GWRITE(FUSE, PROG_PKG_ID, GR_FUSE(PKG_ID));

	GWRITE(FUSE, PROG_BIN_ID, GR_FUSE(BIN_ID));

	GWRITE(FUSE, PROG_RC_JTR_OSC48_CC_TRIM,
		GR_FUSE(RC_JTR_OSC48_CC_TRIM));
	GWRITE(FUSE, PROG_RC_JTR_OSC48_CC_EN, GR_FUSE(RC_JTR_OSC48_CC_EN));
	GWRITE(FUSE, PROG_RC_JTR_OSC60_CC_TRIM,
		GR_FUSE(RC_JTR_OSC60_CC_TRIM));
	GWRITE(FUSE, PROG_RC_JTR_OSC60_CC_EN, GR_FUSE(RC_JTR_OSC60_CC_EN));
	GWRITE(FUSE, PROG_RC_TIMER_OSC48_CC_TRIM,
		GR_FUSE(RC_TIMER_OSC48_CC_TRIM));
	GWRITE(FUSE, PROG_RC_TIMER_OSC48_CC_EN,
		GR_FUSE(RC_TIMER_OSC48_CC_EN));
	GWRITE(FUSE, PROG_RC_TIMER_OSC48_FC_TRIM,
		GR_FUSE(RC_TIMER_OSC48_FC_TRIM));
	GWRITE(FUSE, PROG_RC_TIMER_OSC48_FC_EN,
		GR_FUSE(RC_TIMER_OSC48_FC_EN));
	GWRITE(FUSE, PROG_RC_RTC_OSC256K_CC_TRIM,
		GR_FUSE(RC_RTC_OSC256K_CC_TRIM));
	GWRITE(FUSE, PROG_RC_RTC_OSC256K_CC_EN,
		GR_FUSE(RC_RTC_OSC256K_CC_EN));

	GWRITE(FUSE, PROG_SEL_VREG_REG_EN, GR_FUSE(SEL_VREG_REG_EN));
	GWRITE(FUSE, PROG_SEL_VREF_REG, GR_FUSE(SEL_VREF_REG));
	GWRITE(FUSE, PROG_SEL_VREF_BATMON_EN, GR_FUSE(SEL_VREF_BATMON_EN));
	GWRITE(FUSE, PROG_SEL_VREF_BATMON, GR_FUSE(SEL_VREF_BATMON));

	GWRITE(FUSE, PROG_X_OSC_LDO_CTRL_EN, GR_FUSE(X_OSC_LDO_CTRL_EN));
	GWRITE(FUSE, PROG_X_OSC_LDO_CTRL, GR_FUSE(X_OSC_LDO_CTRL));

	GWRITE(FUSE, PROG_TEMP_OFFSET_CAL, GR_FUSE(TEMP_OFFSET_CAL));

	GWRITE(FUSE, PROG_TRNG_LDO_CTRL_EN, GR_FUSE(TRNG_LDO_CTRL_EN));
	GWRITE(FUSE, PROG_TRNG_LDO_CTRL, GR_FUSE(TRNG_LDO_CTRL));
	GWRITE(FUSE, PROG_TRNG_ANALOG_CTRL_EN, GR_FUSE(TRNG_ANALOG_CTRL_EN));
	GWRITE(FUSE, PROG_TRNG_ANALOG_CTRL, GR_FUSE(TRNG_ANALOG_CTRL));

	GWRITE(FUSE, PROG_EXT_XTAL_PDB, GR_FUSE(EXT_XTAL_PDB));

	GWRITE(FUSE, PROG_DIS_EXT_XTAL_CLK_TREE,
		GR_FUSE(DIS_EXT_XTAL_CLK_TREE));

	GWRITE(FUSE, PROG_OBFUSCATION_EN, GR_FUSE(OBFUSCATION_EN));

	/* OBS fuses can't be read so initialize them to some nonzero value */
	GWRITE(FUSE, PROG_OBS0, 3);
	GWRITE(FUSE, PROG_OBS1, 3);
	GWRITE(FUSE, PROG_OBS2, 3);
	GWRITE(FUSE, PROG_OBS3, 3);
	GWRITE(FUSE, PROG_OBS4, 3);
	GWRITE(FUSE, PROG_OBS5, 3);
	GWRITE(FUSE, PROG_OBS6, 3);
	GWRITE(FUSE, PROG_OBS7, 3);

	GWRITE(FUSE, PROG_HIK_CREATE_LOCK, GR_FUSE(HIK_CREATE_LOCK));

	GWRITE(FUSE, PROG_BNK2_INTG_CHKSUM, GR_FUSE(BNK2_INTG_CHKSUM));
	GWRITE(FUSE, PROG_BNK2_INTG_LOCK, GR_FUSE(BNK2_INTG_LOCK));

	GWRITE(FUSE, PROG_TESTMODE_OTPW_DIS, GR_FUSE(TESTMODE_OTPW_DIS));

	GWRITE(FUSE, PROG_HKEY_WDOG_TIMER_EN, GR_FUSE(HKEY_WDOG_TIMER_EN));

	GWRITE(FUSE, PROG_FLASH_PERSO_PAGE_LOCK,
		GR_FUSE(FLASH_PERSO_PAGE_LOCK));

	GWRITE(FUSE, PROG_ALERT_RSP_CFG, GR_FUSE(ALERT_RSP_CFG));

	GWRITE(FUSE, PROG_BNK3_INTG_CHKSUM, GR_FUSE(BNK3_INTG_CHKSUM));
	GWRITE(FUSE, PROG_BNK3_INTG_LOCK, GR_FUSE(BNK3_INTG_LOCK));

	GWRITE(FUSE, PROG_FW_DEFINED_DATA_BLK0,
		GR_FUSE(FW_DEFINED_DATA_BLK0));
	GWRITE(FUSE, PROG_FW_DEFINED_BROM_ERR_RESPONSE,
		GR_FUSE(FW_DEFINED_BROM_ERR_RESPONSE));
	GWRITE(FUSE, PROG_FW_DEFINED_BROM_APPLYSEC,
		GR_FUSE(FW_DEFINED_BROM_APPLYSEC));
	GWRITE(FUSE, PROG_FW_DEFINED_BROM_CONFIG0,
		GR_FUSE(FW_DEFINED_BROM_CONFIG0));
	GWRITE(FUSE, PROG_FW_DEFINED_BROM_CONFIG1,
		GR_FUSE(FW_DEFINED_BROM_CONFIG1));

	GWRITE(FUSE, PROG_RBOX_MODE_DBG_OVRD_DIS,
		GR_FUSE(RBOX_MODE_DBG_OVRD_DIS));
	GWRITE(FUSE, PROG_RBOX_MODE_OUTPUT_OVRD_DIS,
		GR_FUSE(RBOX_MODE_OUTPUT_OVRD_DIS));
	GWRITE(FUSE, PROG_RBOX_CLK10HZ_COUNT, GR_FUSE(RBOX_CLK10HZ_COUNT));
	GWRITE(FUSE, PROG_RBOX_SHORT_DELAY_COUNT,
		GR_FUSE(RBOX_SHORT_DELAY_COUNT));
	GWRITE(FUSE, PROG_RBOX_LONG_DELAY_COUNT,
		GR_FUSE(RBOX_LONG_DELAY_COUNT));
	GWRITE(FUSE, PROG_RBOX_DEBOUNCE_PERIOD,
		GR_FUSE(RBOX_DEBOUNCE_PERIOD));
	GWRITE(FUSE, PROG_RBOX_DEBOUNCE_BYPASS_PWRB,
		GR_FUSE(RBOX_DEBOUNCE_BYPASS_PWRB));
	GWRITE(FUSE, PROG_RBOX_DEBOUNCE_BYPASS_KEY0,
		GR_FUSE(RBOX_DEBOUNCE_BYPASS_KEY0));
	GWRITE(FUSE, PROG_RBOX_DEBOUNCE_BYPASS_KEY1,
		GR_FUSE(RBOX_DEBOUNCE_BYPASS_KEY1));
	GWRITE(FUSE, PROG_RBOX_KEY_COMBO0_VAL, GR_FUSE(RBOX_KEY_COMBO0_VAL));
	GWRITE(FUSE, PROG_RBOX_KEY_COMBO1_VAL, GR_FUSE(RBOX_KEY_COMBO1_VAL));
	GWRITE(FUSE, PROG_RBOX_KEY_COMBO2_VAL, GR_FUSE(RBOX_KEY_COMBO2_VAL));
	GWRITE(FUSE, PROG_RBOX_KEY_COMBO0_HOLD,
		GR_FUSE(RBOX_KEY_COMBO0_HOLD));
	GWRITE(FUSE, PROG_RBOX_KEY_COMBO1_HOLD,
		GR_FUSE(RBOX_KEY_COMBO1_HOLD));
	GWRITE(FUSE, PROG_RBOX_KEY_COMBO2_HOLD,
		GR_FUSE(RBOX_KEY_COMBO2_HOLD));
	GWRITE(FUSE, PROG_RBOX_BLOCK_KEY0_SEL, GR_FUSE(RBOX_BLOCK_KEY0_SEL));
	GWRITE(FUSE, PROG_RBOX_BLOCK_KEY1_SEL, GR_FUSE(RBOX_BLOCK_KEY1_SEL));
	GWRITE(FUSE, PROG_RBOX_BLOCK_KEY0_VAL, GR_FUSE(RBOX_BLOCK_KEY0_VAL));
	GWRITE(FUSE, PROG_RBOX_BLOCK_KEY1_VAL, GR_FUSE(RBOX_BLOCK_KEY1_VAL));
	GWRITE(FUSE, PROG_RBOX_POL_AC_PRESENT, GR_FUSE(RBOX_POL_AC_PRESENT));
	GWRITE(FUSE, PROG_RBOX_POL_PWRB_IN, GR_FUSE(RBOX_POL_PWRB_IN));
	GWRITE(FUSE, PROG_RBOX_POL_PWRB_OUT, GR_FUSE(RBOX_POL_PWRB_OUT));
	GWRITE(FUSE, PROG_RBOX_POL_KEY0_IN, GR_FUSE(RBOX_POL_KEY0_IN));
	GWRITE(FUSE, PROG_RBOX_POL_KEY0_OUT, GR_FUSE(RBOX_POL_KEY0_OUT));
	GWRITE(FUSE, PROG_RBOX_POL_KEY1_IN, GR_FUSE(RBOX_POL_KEY1_IN));
	GWRITE(FUSE, PROG_RBOX_POL_KEY1_OUT, GR_FUSE(RBOX_POL_KEY1_OUT));
	GWRITE(FUSE, PROG_RBOX_POL_EC_RST, GR_FUSE(RBOX_POL_EC_RST));
	GWRITE(FUSE, PROG_RBOX_POL_BATT_DISABLE,
		GR_FUSE(RBOX_POL_BATT_DISABLE));
	GWRITE(FUSE, PROG_RBOX_TERM_AC_PRESENT,
		GR_FUSE(RBOX_TERM_AC_PRESENT));
	GWRITE(FUSE, PROG_RBOX_TERM_ENTERING_RW,
		GR_FUSE(RBOX_TERM_ENTERING_RW));
	GWRITE(FUSE, PROG_RBOX_TERM_PWRB_IN, GR_FUSE(RBOX_TERM_PWRB_IN));
	GWRITE(FUSE, PROG_RBOX_TERM_PWRB_OUT, GR_FUSE(RBOX_TERM_PWRB_OUT));
	GWRITE(FUSE, PROG_RBOX_TERM_KEY0_IN, GR_FUSE(RBOX_TERM_KEY0_IN));
	GWRITE(FUSE, PROG_RBOX_TERM_KEY0_OUT, GR_FUSE(RBOX_TERM_KEY0_OUT));
	GWRITE(FUSE, PROG_RBOX_TERM_KEY1_IN, GR_FUSE(RBOX_TERM_KEY1_IN));
	GWRITE(FUSE, PROG_RBOX_TERM_KEY1_OUT, GR_FUSE(RBOX_TERM_KEY1_OUT));
	GWRITE(FUSE, PROG_RBOX_DRIVE_PWRB_OUT, GR_FUSE(RBOX_DRIVE_PWRB_OUT));
	GWRITE(FUSE, PROG_RBOX_DRIVE_KEY0_OUT, GR_FUSE(RBOX_DRIVE_KEY0_OUT));
	GWRITE(FUSE, PROG_RBOX_DRIVE_KEY1_OUT, GR_FUSE(RBOX_DRIVE_KEY1_OUT));
	GWRITE(FUSE, PROG_RBOX_DRIVE_EC_RST, GR_FUSE(RBOX_DRIVE_EC_RST));
	GWRITE(FUSE, PROG_RBOX_DRIVE_BATT_DISABLE,
		GR_FUSE(RBOX_DRIVE_BATT_DISABLE));

	GWRITE(FUSE, PROG_BNK4_INTG_CHKSUM, GR_FUSE(BNK4_INTG_CHKSUM));
	GWRITE(FUSE, PROG_BNK4_INTG_LOCK, GR_FUSE(BNK4_INTG_LOCK));

	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK0,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK0));
	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK1,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK1));
	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK2,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK2));
	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK3,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK3));
	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK4,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK4));
	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK5,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK5));
	GWRITE(FUSE, PROG_FW_DEFINED_DATA_EXTRA_BLK6,
		GR_FUSE(FW_DEFINED_DATA_EXTRA_BLK6));
}

void fuse_override_start(void)
{
	/* Start fuse override */
	GWRITE(FUSE, OVERRIDE_START, 0x894e4cf3);

	/* Wait until override is finished */
	while (!(GREAD(FUSE, STATUS) & (GC_FUSE_STATUS_OVERRIDE_DONE_MASK)))
		;
}
