/* Copyright 2016 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#include "clock.h"
#include "gpio.h"
#include "hooks.h"
#include "rbox.h"
#include "task.h"

#ifdef CONFIG_RBOX_DEBUG
RBOX_INT(KEY0_IN_FED, "KEY0 pressed");
RBOX_INT(KEY0_IN_RED, "KEY0 released");
RBOX_INT(KEY1_IN_FED, "KEY1 pressed");
RBOX_INT(KEY1_IN_RED, "KEY1 released");
RBOX_INT(PWRB_IN_FED, "PWRB pressed");
RBOX_INT(PWRB_IN_RED, "PWRB released");
RBOX_INT(EC_RST_RED, "EC RST rising");
RBOX_INT(EC_RST_FED, "EC RST falling");
RBOX_INT(AC_PRESENT_RED, "AC attached");
RBOX_INT(AC_PRESENT_FED, "AC detached");

RBOX_INT(BUTTON_COMBO0_RDY, "COMBO0");
RBOX_INT(BUTTON_COMBO1_RDY, "COMBO1");
RBOX_INT(BUTTON_COMBO2_RDY, "COMBO2");

static void enable_interrupts(void)
{
	ENABLE_INT_RF(ENTERING_RW);
	ENABLE_INT_RF(AC_PRESENT);
	ENABLE_INT_RF(PWRB_IN);
	ENABLE_INT_RF(KEY1_IN);
	ENABLE_INT_RF(KEY0_IN);
	ENABLE_INT_RF(EC_RST);
	ENABLE_INT(BUTTON_COMBO0_RDY);
	ENABLE_INT(BUTTON_COMBO1_RDY);
	ENABLE_INT(BUTTON_COMBO2_RDY);

	task_enable_irq(GC_IRQNUM_RBOX0_INTR_AC_PRESENT_FED_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_AC_PRESENT_RED_INT);

	task_enable_irq(GC_IRQNUM_RBOX0_INTR_PWRB_IN_FED_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_PWRB_IN_RED_INT);

	task_enable_irq(GC_IRQNUM_RBOX0_INTR_KEY0_IN_RED_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_KEY0_IN_FED_INT);

	task_enable_irq(GC_IRQNUM_RBOX0_INTR_KEY1_IN_RED_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_KEY1_IN_FED_INT);

	task_enable_irq(GC_IRQNUM_RBOX0_INTR_EC_RST_RED_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_EC_RST_FED_INT);

	task_enable_irq(GC_IRQNUM_RBOX0_INTR_BUTTON_COMBO0_RDY_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_BUTTON_COMBO1_RDY_INT);
	task_enable_irq(GC_IRQNUM_RBOX0_INTR_BUTTON_COMBO2_RDY_INT);
}
#endif

static void rbox_release_ec_reset(void)
{
	/* Let the EC go. */
	GREG32(RBOX, ASSERT_EC_RST) = 0;

	/* And unfreeze the PINMUX */
	GREG32(PINMUX, HOLD) = 0;
}
DECLARE_HOOK(HOOK_INIT, rbox_release_ec_reset, HOOK_PRIO_LAST);

static void rbox_init(void)
{
	/* Enable RBOX */
	clock_enable_module(MODULE_RBOX, 1);

	/* Clear existing interrupts */
	GWRITE(RBOX, WAKEUP_CLEAR, 1);
	GWRITE(RBOX, WAKEUP_CLEAR, 0);
	GWRITE(RBOX, INT_STATE, 1);

	/* Override rbox fuses and setup correct behavior */
	GWRITE(RBOX, DEBUG_CLK10HZ_COUNT, 0x63ff);
	GWRITE(RBOX, DEBUG_SHORT_DELAY_COUNT, 0x4ff);
	GWRITE(RBOX, DEBUG_LONG_DELAY_COUNT, 0x31);
	GWRITE(RBOX, DEBUG_DEBOUNCE, 0x4);
	GWRITE(RBOX, DEBUG_KEY_COMBO0, 0xC0);
	GWRITE(RBOX, DEBUG_KEY_COMBO1, 0x0);
	GWRITE(RBOX, DEBUG_KEY_COMBO2, 0x0);
	/* DEBUG_BLOCK_OUTPUT value should be 0x7 */
	GWRITE(RBOX, DEBUG_BLOCK_OUTPUT,
	       GC_RBOX_DEBUG_BLOCK_OUTPUT_KEY0_SEL_MASK |
	       GC_RBOX_DEBUG_BLOCK_OUTPUT_KEY1_SEL_MASK |
	       GC_RBOX_DEBUG_BLOCK_OUTPUT_KEY0_VAL_MASK );
	/* DEBUG_POL value should be 0x21 */
	GWRITE(RBOX, DEBUG_POL,
	       0x1 << GC_RBOX_DEBUG_POL_AC_PRESENT_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_PWRB_IN_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_PWRB_OUT_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_KEY0_IN_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_KEY0_OUT_LSB |
	       0x1 << GC_RBOX_DEBUG_POL_KEY1_IN_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_KEY1_OUT_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_EC_RST_LSB |
	       0x0 << GC_RBOX_DEBUG_POL_BATT_DISABLE_LSB);
	/* DEBUG_TERM value should be 0x1204 */
	GWRITE(RBOX, DEBUG_TERM,
	       0x0 << GC_RBOX_DEBUG_TERM_AC_PRESENT_LSB |
	       0x1 << GC_RBOX_DEBUG_TERM_ENTERING_RW_LSB |
	       0x0 << GC_RBOX_DEBUG_TERM_PWRB_IN_LSB |
	       0x0 << GC_RBOX_DEBUG_TERM_PWRB_OUT_LSB |
	       0x2 << GC_RBOX_DEBUG_TERM_KEY0_IN_LSB |
	       0x0 << GC_RBOX_DEBUG_TERM_KEY0_OUT_LSB |
	       0x1 << GC_RBOX_DEBUG_TERM_KEY1_IN_LSB |
	       0x0 << GC_RBOX_DEBUG_TERM_KEY1_IN_LSB);
	/* DEBUG_BLOCK_OUTPUT value should be 0x157 */
	GWRITE(RBOX, DEBUG_DRIVE,
	       0x3 << GC_RBOX_DEBUG_DRIVE_PWRB_OUT_LSB |
	       0x1 << GC_RBOX_DEBUG_DRIVE_KEY0_OUT_LSB |
	       0x1 << GC_RBOX_DEBUG_DRIVE_KEY1_OUT_LSB |
	       0x1 << GC_RBOX_DEBUG_DRIVE_EC_RST_LSB |
	       0x1 << GC_RBOX_DEBUG_DRIVE_BATT_DISABLE_LSB );
	/* FUSE_CTRL value should be 0x3 */
	GWRITE(RBOX, FUSE_CTRL,
	       GC_RBOX_FUSE_CTRL_OVERRIDE_FUSE_MASK |
	       GC_RBOX_FUSE_CTRL_OVERRIDE_FUSE_READY_MASK );

#ifdef CONFIG_RBOX_DEBUG
	enable_interrupts();
#endif
}
DECLARE_HOOK(HOOK_INIT, rbox_init, HOOK_PRIO_DEFAULT - 1);
