# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ANRAGGAR=y

# Disable sub board configurations
CONFIG_NISSA_SUB_BOARD=n

CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

CONFIG_PLATFORM_EC_OCPC=n
# CONFIG_PLATFORM_EC_HIBERNATE_PSL=y
CONFIG_PLATFORM_EC_CHARGER_SM5803=n
CONFIG_PLATFORM_EC_CHARGER_SINGLE_CHIP=y
CONFIG_PLATFORM_EC_USBC_VCONN=y
CONFIG_PLATFORM_EC_USB_PD_TCPC_VCONN=n
CONFIG_PLATFORM_EC_USBC_PPC_SYV682C=y
CONFIG_PLATFORM_EC_USB_PD_VBUS_DETECT_CHARGER=n
CONFIG_PLATFORM_EC_USB_PD_VBUS_DETECT_PPC=y
CONFIG_PLATFORM_EC_USB_PD_INITIAL_DEBUG_LEVEL=3

# Ensure recovery key combination (esc+refresh+power) is reliable: b/236580049
CONFIG_PLATFORM_EC_KEYBOARD_PWRBTN_ASSERTS_KSI2=y

# Sensor drivers
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCEL_BMA4XX=y
CONFIG_PLATFORM_EC_MAX_SENSOR_FREQ_MILLIHZ=100000

# No fan supported, and tach is default-enabled
CONFIG_TACH_IT8XXX2=n

CONFIG_PLATFORM_EC_CHARGER_BQ25720=y
CONFIG_PLATFORM_EC_USBC_PPC=y
CONFIG_PLATFORM_EC_USBC_PPC_SYV682X=y
CONFIG_PLATFORM_EC_TCPC_INTERRUPT=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y

CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_USBA=n
CONFIG_PLATFORM_EC_USB_PORT_ENABLE_DYNAMIC=n

CONFIG_PLATFORM_EC_KEYBOARD_BACKLIGHT=n
CONFIG_PLATFORM_EC_KBLIGHT_ENABLE_PIN=n
