#!/bin/bash
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# From ISH 5.8, CSE requires ISH main firmware to include a header
# for host loading purpose. The header is generated by MEU.
# This script appends a pre-built header to ISH image.
# Run the script with two arguments:
# Usage: sign_ish_main.sh <Path to ISH Image> <Header File>

function die() {
    echo "Failed to append ISH header"
    exit 1
}

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <PATH to ISH Image> <Header File>"
    die
fi

ISH_INPUT_BIN="$1/ish_fw.bin"
ISH_OUTPUT_BIN=$(mktemp)
ISH_HEADER_BIN=$2

echo "${ISH_OUTPUT_BIN}"
echo "${ISH_HEADER_BIN}"

if [ ! -f "${ISH_HEADER_BIN}" ]; then
    echo "Header file is missing"
    die
fi

if [ ! -f "${ISH_INPUT_BIN}" ]; then
    echo "${ISH_INPUT_BIN} is missing"
    die
fi

# Append header
cat "${ISH_HEADER_BIN}" "${ISH_INPUT_BIN}" > "${ISH_OUTPUT_BIN}"
mv "${ISH_OUTPUT_BIN}" "${ISH_INPUT_BIN}"
