#!/bin/bash
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# From ISH 5.8, CSE requires ISH main firmware to include a header
# for host loading purpose. The header is generated by MEU.
# This script appends a pre-built header to ISH image.
# Run the script with three arguments:
# Usage: sign_ish_main.sh <ISH BOARD> <Path to ISH Image> <Path to header>

function die() {
        echo "Failed to append ISH header"
        exit 1
}

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <ISH BOARD> <PATH to ISH Image> <Path to header>"
    die
fi

ISH_INPUT_BIN="$2/ish_fw.bin"
ISH_OUTPUT_BIN="ish_output.bin"
ISH_HEADER_DIR=$3

if [ "$1" == "intel_ish_5_8_0" ]; then
    ISH_HEADER_BIN="${ISH_HEADER_DIR}/ish_header_5_8.bin"
fi

if [ ! -f "${ISH_HEADER_BIN}" ]; then
    echo "Header file is missing"
    die
fi

if [ ! -f "${ISH_INPUT_BIN}" ]; then
    echo "ish_fw.bin is missing"
    die
fi

# Append header
cat "${ISH_HEADER_BIN}" "${ISH_INPUT_BIN}" > "${ISH_OUTPUT_BIN}"
mv "${ISH_OUTPUT_BIN}" ish_fw.bin
