# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_SKYWALKER=y

# Bring up options
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Debug options and features; can be disabled to save memory or once bringup
# is complete.
CONFIG_SHELL_MINIMAL=y

# PWM
CONFIG_PWM=n

# Math
CONFIG_PLATFORM_EC_MATH_UTIL=y

# Power sequencing
CONFIG_PLATFORM_EC_POWERSEQ_MT8196=y
CONFIG_PLATFORM_EC_POWERSEQ_S4=n

# Switch
CONFIG_PLATFORM_EC_LID_SWITCH=y

# External power
CONFIG_PLATFORM_EC_BACKLIGHT_LID=n

# Keyboard
CONFIG_CROS_KB_RAW_NPCX_KSO_HIGH_DRIVE=n

CONFIG_SYSCON=y

CONFIG_NAMED_ADC_CHANNELS=n

CONFIG_USBC_PDC_RTS54XX_FW_UPDATER=y
