# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_SKYWALKER=y

CONFIG_PLATFORM_EC_ACCELGYRO_BMI3XX=y
CONFIG_PLATFORM_EC_ACCELGYRO_BMI_COMM_I2C=y

CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y

# Buttons
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

# PDC
CONFIG_PLATFORM_EC_TIMER=y
CONFIG_PLATFORM_EC_USB_PD_LOGGING=n

CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=n
CONFIG_PLATFORM_EC_USB_PD_TCPMV2=n
CONFIG_PLATFORM_EC_USB_PD_CONTROLLER=y

CONFIG_UCSI_PPM=y

CONFIG_PLATFORM_EC_USB_MUX_TASK=y
CONFIG_PDC_POWER_MGMT_USB_MUX=y
