# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_PLATFORM_EC_LTO=n

# Shell features
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_KERNEL_SHELL=y

CONFIG_I2C_DUMP_MESSAGES=y
CONFIG_I2C_LOG_LEVEL_DBG=y

# Bring up configs
CONFIG_SHELL_HISTORY_BUFFER=256
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Disable options not yet configured
CONFIG_AP=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_CHARGEN=n
CONFIG_PLATFORM_EC_CBI=n
CONFIG_NAMED_ADC_CHANNELS=n
CONFIG_PWM=n
CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_PLATFORM_EC_POWER_BUTTON=n
CONFIG_PLATFORM_EC_SWITCH=n
CONFIG_PLATFORM_EC_VBOOT_EFS2=n

# PDC

# Disable Power Delivery Function (refer to anakin)
CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=n
CONFIG_PLATFORM_EC_USBC_SS_MUX=n
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_USB_MUX_TASK=n
#def y
CONFIG_PLATFORM_EC_USB_PD_DP_MODE=n
#def y
CONFIG_PLATFORM_EC_USB_PD_HOST_CMD=n
CONFIG_PLATFORM_EC_USB_PD_REQUIRE_AP_MODE_ENTRY=n
CONFIG_PLATFORM_EC_USB_PD_REV30=y
#def y
CONFIG_PLATFORM_EC_USBC_RETIMER_FW_UPDATE=n
CONFIG_PLATFORM_EC_USB_PD_TBT_COMPAT_MODE=n
CONFIG_PLATFORM_EC_USB_PD_USB4=n
CONFIG_PLATFORM_EC_USB_PD_3A_PORTS=0

# PD common
## CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=n
# CONFIG_PLATFORM_EC_CONSOLE_CMD_PD=n
# CONFIG_PLATFORM_EC_USBC_VCONN=n
# CONFIG_PLATFORM_EC_USB_PD_DUAL_ROLE=n
# CONFIG_PLATFORM_EC_USB_PD_DPS=n
# CONFIG_PLATFORM_EC_USB_PD_DUAL_ROLE_AUTO_TOGGLE=n
# CONFIG_PLATFORM_EC_USB_PD_EXTENDED_MESSAGES=n
# CONFIG_PLATFORM_EC_USB_PD_ALT_MODE=n
# CONFIG_PLATFORM_EC_USB_PD_ALT_MODE_DFP=n
# CONFIG_PLATFORM_EC_USB_PD_DISCOVERY=n
# CONFIG_PLATFORM_EC_USB_PD_TCPMV2=n
# CONFIG_PLATFORM_EC_USB_TYPEC_SM=n
# CONFIG_PLATFORM_EC_USB_PRL_SM=n
# CONFIG_PLATFORM_EC_USB_PE_SM=n
# CONFIG_PLATFORM_EC_USB_DPM_SM=n
# CONFIG_PLATFORM_EC_USB_PD_DECODE_SOP=n
# CONFIG_PLATFORM_EC_USB_DRP_ACC_TRYSRC=n
CONFIG_PLATFORM_EC_USBC=y                   #support usb-c function
CONFIG_PLATFORM_EC_USB_PD_CONTROLLER=y      #use TCPMv2 or PDC
CONFIG_PLATFORM_EC_CONSOLE_CMD_PDC_TYPEC=y  #solve build error

# PD controller sub system
#def y
CONFIG_USB_PDC_POWER_MGMT=y             #pd_controller folder: need en charger, include pdc console, host cmd, pdc dpm
CONFIG_PDC_RUNTIME_PORT_CONFIG=y        #solve build error
#def y
CONFIG_UCSI_PPM=y                       #ucsi folder

# PDC driver
# CONFIG_USBC_PDC_IT52XX=y
CONFIG_USBC_PDC_RTS54XX=y
CONFIG_PLATFORM_EC_USB_PD_DISCHARGE=n
CONFIG_PLATFORM_EC_USB_PD_DISCHARGE_GPIO=n
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_PDC=y  #does it52xx support this?
