# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Variant config
CONFIG_BOARD_KINGLER=y

# LED
CONFIG_PLATFORM_EC_LED_PWM=y

# kingler rev0 uses H1 and rev1 uses D2.
# Disable this config for D2.
CONFIG_PLATFORM_EC_BOARD_RESET_AFTER_POWER_ON=n
