# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Skyrim reference-board-specific Kconfig settings.
CONFIG_BOARD_SKYRIM=y

# TODO(b/215404321): Remove later in board development
CONFIG_PLATFORM_EC_EEPROM_CBI_WP=y
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# LED
CONFIG_PLATFORM_EC_LED_DT=y

# Only Skyrim has the PCT2075
CONFIG_PLATFORM_EC_TEMP_SENSOR_PCT2075=y

CONFIG_PLATFORM_EC_USBC_RETIMER_ANX7483=y

# These are debug options that happen to be expensive
# in terms of flash space. Turn on based on demand.
CONFIG_FLASH_PAGE_LAYOUT=n # 1876 bytes
CONFIG_FLASH_SHELL=n # 1852 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_ACCEL_INFO=n # 656 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_CRASH=n # 460 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_FLASHINFO=n # 524 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_KEYBOARD=n # 2524 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_MEM=n # 896 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_PD=n # 3604 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_TCPC_DUMP=n # 1180 bytes
CONFIG_PLATFORM_EC_CONSOLE_CMD_USB_PD_CABLE=n # 1104 bytes
CONFIG_PLATFORM_EC_USB_PD_HOST_CMD=n # 3092 bytes
CONFIG_THREAD_MONITOR=n # 1548 bytes
