# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Pujjolo reference-board-specific Kconfig settings.
CONFIG_BOARD_PUJJOLO=y

# CBI
CONFIG_PLATFORM_EC_CBI_TRANSFER_EEPROM_FLASH=y
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y
CONFIG_PLATFORM_EC_EEPROM_CBI_WP=y

# Battery
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_REVIVE_DISCONNECT=y

#Button
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n

#Charger / Power Delivery
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_PDC=y
CONFIG_PLATFORM_EC_CONSOLE_CMD_CHARGEN=y
CONFIG_PLATFORM_EC_CONFIG_USB_PD_3A_PORTS=1
CONFIG_PLATFORM_EC_USB_PD_FRS=y
CONFIG_PLATFORM_EC_PD_MAX_POWER_MW=65000
CONFIG_PLATFORM_EC_PD_MAX_VOLTAGE_MV=21000
CONFIG_PLATFORM_EC_PD_MAX_CURRENT_MA=3250

#Hibernate
CONFIG_PLATFORM_EC_HIBERNATE_PSL=y

#Tablet Mode
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y

# Keyboard
CONFIG_INPUT=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_CROS_EC_KEYBOARD_INPUT=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_SHELL_KBD_MATRIX_STATE=y
CONFIG_PLATFORM_EC_KEYBOARD_REFRESH_ROW3=y
CONFIG_PLATFORM_EC_KEYBOARD=y

#Lid
CONFIG_PLATFORM_EC_BACKLIGHT_LID=y
CONFIG_PLATFORM_EC_KBLIGHT_ENABLE_PIN=y
CONFIG_PLATFORM_EC_LID_SWITCH=y
