# DKMS configuration file for i2c-pseudo.
#
# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

PACKAGE_NAME="i2c-pseudo"
PACKAGE_VERSION="2"

BUILT_MODULE_NAME[0]="${PACKAGE_NAME}"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
DEST_MODULE_LOCATION[0]=/extra

PATCH[0]="compat-pre-5.15.patch"
PATCH_MATCH[0]="([234]\..+)|(5\.(1|2|3|4|5|6|7|8|9|10|11|12|13|14)\..+)"

AUTOINSTALL=yes
