# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_FLASH_IT8XXX2=y
CONFIG_CROS_SYSTEM_IT8XXX2=y
CONFIG_FPU=y
# rv32iafc/ilp32f is not supported by the toolchain, so use soft-float
CONFIG_FLOAT_HARD=n

# Allow more time for the charger to stabilise
CONFIG_PLATFORM_EC_POWER_BUTTON_INIT_TIMEOUT=5

# ITE has more space, so don't restrict shell
CONFIG_SHELL_MINIMAL=n

# RAM savings, since this chip is tight on available RAM.
# It's useful to store a lot of logs for the host to request, but the default 4k
# is pretty large.
CONFIG_PLATFORM_EC_HOSTCMD_CONSOLE_BUF_SIZE=2048
# Our threads have short names, save 20 bytes per thread
CONFIG_THREAD_MAX_NAME_LEN=12
# Task stacks, tuned by experiment. Most expanded to prevent overflow, and a few
# shrunk to save RAM.
CONFIG_AP_PWRSEQ_STACK_SIZE=1408
CONFIG_TASK_HOSTCMD_STACK_SIZE=1280
CONFIG_TASK_PD_INT_STACK_SIZE=1280

# TCPC+PPC: ITE on-chip for C0
CONFIG_PLATFORM_EC_USB_PD_VBUS_DETECT_CHARGER=n
CONFIG_PLATFORM_EC_USBC_PPC=y
CONFIG_PLATFORM_EC_USBC_PPC_SYV682X=y
CONFIG_PLATFORM_EC_USB_PD_DISCHARGE=y
CONFIG_PLATFORM_EC_USB_PD_DISCHARGE_PPC=y
CONFIG_PLATFORM_EC_USB_PD_VBUS_DETECT_PPC=y
# SM5803 controls power path on both ports
CONFIG_PLATFORM_EC_USB_PD_5V_CHARGER_CTRL=y

# VSENSE
CONFIG_VCMP_IT8XXX2_WORKQUEUE=y
CONFIG_VCMP_IT8XXX2_WORKQUEUE_PRIORITY=12
