/* Copyright 2023 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Intel MTL-P-RVP board-specific configuration */

#ifndef __CROS_EC_BOARD_H
#define __CROS_EC_BOARD_H

#undef CONFIG_ADC
#undef CONFIG_HIBERNATE
#undef CONFIG_SPI_FLASH

/* GPIO64/65 are used as UART pins. */
#define NPCX_UART_MODULE2 1

/* Power sequencing */
#define GPIO_EC_SPI_OE_N GPIO_EC_SPI_OE_MECC_R
#define GPIO_PG_EC_ALL_SYS_PWRGD GPIO_ALL_SYS_PWRGD
#define GPIO_PG_EC_RSMRST_ODL GPIO_RSMRST_PWRGD
#define GPIO_PCH_SLP_S0_L GPIO_PCH_SLP_S0_N_EC
#define GPIO_SYS_RESET_L GPIO_SYS_RST_ODL_EC
#define GPIO_PCH_RSMRST_L GPIO_PM_RSMRST_R_N
#define GPIO_PCH_PWRBTN_L GPIO_PM_PWRBTN_N_EC
#define GPIO_EN_PP3300_A GPIO_EC_DS3_R
#define GPIO_PCH_PWROK GPIO_PCH_PWROK_EC_R
#define GPIO_CPU_PROCHOT GPIO_PROCHOT_EC
#define GPIO_POWER_BUTTON_L GPIO_SMC_ONOFF_N
#define GPIO_LID_OPEN GPIO_SMC_LID

/* eSPI/Host communication */
#define GPIO_PCH_WAKE_L GPIO_PCH_WAKE_N

/* Chipset */
#define CONFIG_CHIPSET_METEORLAKE

/* SoC / PCH */
#define CONFIG_CHIPSET_RESET_HOOK
#define CONFIG_HOST_INTERFACE_ESPI
#define CONFIG_HOST_INTERFACE_ESPI_VW_SLP_S3
#define CONFIG_HOST_INTERFACE_ESPI_VW_SLP_S4
#define CONFIG_HOST_INTERFACE_ESPI_VW_SLP_S5
#define CONFIG_POWER_COMMON
#define CONFIG_POWER_S0IX
#define CONFIG_POWER_S4_RESIDENCY
#define CONFIG_POWER_TRACK_HOST_SLEEP_STATE

/* Board ID */
#define CONFIG_BOARD_VERSION_GPIO

/* Power Button */
#define CONFIG_POWER_BUTTON
#define CONFIG_POWER_BUTTON_X86
#define CONFIG_LID_SWITCH

/* USB mux */
#define CONFIG_USBC_SS_MUX
#define CONFIG_USB_MUX_VIRTUAL
#define CONFIG_USB_PD_HOST_CMD
#undef CONFIG_HOSTCMD_RWHASHPD
#undef CONFIG_EC_CMD_PD_CHIP_INFO
#define CONFIG_USB_PD_TCPM_MTLPD
#define CONFIG_USB_PD_PORT_MAX_COUNT 4

/* I2C ports & Configs */
#define CONFIG_I2C
#define CONFIG_I2C_CONTROLLER
#define I2C_PORT_TYPEC_AIC1 NPCX_I2C_PORT0_0
#define I2C_PORT_SMLINK 5 /* NPCX_I2C_PORT5_0 */

/* Keyboard */
#define CONFIG_KEYBOARD_DISCRETE
#define CONFIG_KEYBOARD_PROTOCOL_8042
#define CONFIG_KEYBOARD_COL2_INVERTED
#define CONFIG_KEYBOARD_PWRBTN_ASSERTS_KSI2

/* Note: Disable CONFIG_IO_EXPANDER when PD drives Keyboard IOEX */
/* #define CONFIG_IO_EXPANDER */

#ifndef __ASSEMBLER__
#include "gpio_signal.h"

enum adc_channel {
	DUMMY,
};

#ifdef CONFIG_IO_EXPANDER
enum mtl_ioex_port {
	IOEX_KBD_GPIO,
	IOEX_PORT_COUNT
};
#define CONFIG_IO_EXPANDER_IT8801
#define CONFIG_IO_EXPANDER_PORT_COUNT IOEX_PORT_COUNT
#define I2C_PORT_KB_DISCRETE NPCX_I2C_PORT7_0
#define KB_DISCRETE_I2C_ADDR_FLAGS IT8801_I2C_ADDR2
#define GPIO_KB_DISCRETE_INT GPIO_IOEX_KBD_INTR_N
#endif

#endif /* !__ASSEMBLER__ */

#endif /* __CROS_EC_BOARD_H */
