// Copyright 2018 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto3";

package fuzz;

message PWResetTree {
  uint32 bits_per_level = 1;
  uint32 height = 2;
}

message PWInsertLeaf {
  uint64 label = 1;
  bytes delay_schedule = 2;
  bytes low_entropy_secret = 3;
  bytes high_entropy_secret = 4;
  bytes reset_secret = 5;
  bytes path_hashes = 6;
}

message PWRemoveLeaf {
  uint64 label = 1;
  bytes leaf_hmac = 2;
  bytes path_hashes = 3;
}

message PWTryAuth {
  uint64 label = 1;
  bytes low_entropy_secret = 2;
  bytes unimported_leaf_data = 3;
}

message PWResetAuth {
  uint64 label = 1;
  bytes reset_secret = 2;
  bytes unimported_leaf_data = 3;
}

message PWGetLog {
  uint32 index_of_root = 1;
}

message PWLogReplay {
  uint32 index_of_root = 1;
}

message PinWeaver {
  uint32 version = 1;
  oneof request {
    PWResetTree reset_tree = 2;
    PWInsertLeaf insert_leaf = 3;
    PWRemoveLeaf remove_leaf = 4;
    PWTryAuth try_auth = 5;
    PWResetAuth reset_auth = 6;
    PWGetLog get_log = 7;
    PWLogReplay log_replay = 8;
  }
}

message RandomBytes {
  bytes value = 1;
}

message SubAction {
  // Allows a logical representation of an action (PinWeaver) or a literal
  // representation (RandomBytes). The logical representation fills out the
  // expected values of particular fields when they are empty or not part of the
  // proto so that the fuzzer can reach parts of the code without having to
  // brute force an HMAC. The literal representation allows for the fuzzer to
  // represent inputs that cannot be represented with the logical
  // representation.
  oneof sub_action {
    RandomBytes random_bytes = 1;
    PinWeaver pinweaver = 2;
  }
}

message FuzzerInput {
  repeated SubAction sub_actions = 1;
}
