# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_DIRKS=y

# No sub-board supported
CONFIG_NISSA_SUB_BOARD=n

# No fan supported, and tach is default-enabled
CONFIG_TACH_IT8XXX2=n

# No charger supported
# Both of these options neeed to be explicity disabled
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_CHARGE_MANAGER=n

# No charger supported
# Both of these options neeed to be explicity disabled
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_CHARGE_MANAGER=n

# USB-C
CONFIG_PLATFORM_EC_USBC_VCONN=y
CONFIG_PLATFORM_EC_USB_PD_TCPMV2=y
CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=y

# USB Type A Features
CONFIG_PLATFORM_EC_USB_PORT_POWER_DUMB=y

# buttons
CONFIG_PLATFORM_EC_DEDICATED_RECOVERY_BUTTON=y
CONFIG_PLATFORM_EC_DEDICATED_RECOVERY_BUTTON_ACTIVE_HIGH=y
CONFIG_PLATFORM_EC_DEDICATED_RECOVERY_BUTTON_2=y

# Required to make it build
CONFIG_PLATFORM_EC_HIBERNATE_PSL=n
