# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_DIRKS=y

# No fan supported, and tach is default-enabled
CONFIG_TACH_IT8XXX2=n

# Both ports use a PI5USB2546 smart switch with CTL1..3 fixed high,
# for SDP2 or CDP only.
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART=y
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART_CDP_SDP_ONLY=y
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART_DEFAULT_CDP=y
CONFIG_PLATFORM_EC_USB_PORT_POWER_SMART_INVERTED=y

# No charger supported
# Both of these options neeed to be explicity disabled
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_CHARGE_MANAGER=n

# No charger supported
# Both of these options neeed to be explicity disabled
CONFIG_PLATFORM_EC_USB_CHARGER=n
CONFIG_PLATFORM_EC_CHARGE_MANAGER=n

# USB-C
CONFIG_PLATFORM_EC_USBC_VCONN=y
CONFIG_PLATFORM_EC_USB_PD_TCPMV2=y
CONFIG_PLATFORM_EC_USB_POWER_DELIVERY=y
