# -*- makefile -*-
# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This makefile is used only by firmware_builder.py to achieve parallelism.
# The paths in this file need to match the ones in firmware_builder.py,
# so be careful.

TWISTER_COMMAND=cd $(PLATFORM_EC) && ./twister --outdir \
	twister-out-$(TOOLCHAIN) -v -i --no-upload-cros-rdb --toolchain \
	$(TOOLCHAIN)
ifdef COVERAGE
TWISTER_COMMAND+=--coverage
endif

PLATFORM_EC=$(abspath ..)
THIRD_PARTY=$(abspath ../../../third_party)
BUILD=$(PLATFORM_EC)/build

GENERATED_AND_SYSTEM_PATTERNS='$(PLATFORM_EC)/build/**' \
	'$(PLATFORM_EC)/twister-out*/**' \
	'/usr/include/**' \
	'/usr/lib/**'
TEST_PATTERNS='$(PLATFORM_EC)/test/**' \
	'$(PLATFORM_EC)/include/tests/**' \
	'$(PLATFORM_EC)/private/test/**' \
	'$(PLATFORM_EC)/private/fingerprint/*/mcutest/**' \
	'$(PLATFORM_EC)/zephyr/test/**' \
	'$(THIRD_PARTY)/zephyr/main/subsys/testsuite/**' \
	'$(PLATFORM_EC)/include/mock/**' \
	'$(PLATFORM_EC)/common/mock/**' \
	'$(PLATFORM_EC)/board/host/**' \
	'$(PLATFORM_EC)/chip/host/**' \
	'$(PLATFORM_EC)/core/host/**' \
	'$(PLATFORM_EC)/zephyr/emul/**' \
	'$(PLATFORM_EC)/zephyr/mock/**' \
	'$(THIRD_PARTY)/zephyr/main/subsys/emul/**' \
	'$(THIRD_PARTY)/zephyr/main/arch/posix/**' \
	'**/*_test.c' \
	'**/*_test.h' \
	'**/*_emul.c' \
	'**/*_emul.h' \
	'$(PLATFORM_EC)/include/test_util.h' \
	'$(PLATFORM_EC)/common/test_util.c' \
	'$(PLATFORM_EC)/zephyr/shim/src/test_util.c' \
	'$(PLATFORM_EC)/zephyr/shim/src/ztest_system.c'

.PHONY: test twister_host twister_llvm legacy_coverage

test: zmake_unit_tests twister_host twister_llvm
ifdef COVERAGE
test: $(BUILD)/zephyr/lcov.info $(BUILD)/zephyr/lcov_no_tests.info
test: $(BUILD)/zephyr/lcov_rpt special_boards
endif

zmake_unit_tests:
	zmake/run_tests.sh

twister_host: TOOLCHAIN=host
twister_host:
	+$(TWISTER_COMMAND)

twister_llvm: TOOLCHAIN=llvm
twister_llvm:
	+$(TWISTER_COMMAND)

legacy_coverage:
	$(MAKE) -C .. test-coverage

$(BUILD)/zephyr/all_tests.info: twister_host twister_llvm legacy_coverage
	/usr/bin/lcov -o $@ --rc lcov_branch_coverage=1 \
	-a $(BUILD)/coverage/lcov.info -a $(PLATFORM_EC)/twister-out-llvm/coverage.info \
	-a $(PLATFORM_EC)/twister-out-host/coverage.info

$(BUILD)/zephyr/zephyr_merged.info: $(BUILD)/zephyr/all_tests.info $(BUILD)/zephyr/all_builds.info
	/usr/bin/lcov -o $@ --rc lcov_branch_coverage=1 \
	-a $(BUILD)/zephyr/all_tests.info -a $(BUILD)/zephyr/all_builds.info

$(BUILD)/zephyr/lcov.info: $(BUILD)/zephyr/zephyr_merged.info
	/usr/bin/lcov -o $@ --rc lcov_branch_coverage=1 \
	-r $(BUILD)/zephyr/zephyr_merged.info \
	$(GENERATED_AND_SYSTEM_PATTERNS)

$(BUILD)/zephyr/lcov_no_tests.info: $(BUILD)/zephyr/lcov.info
	/usr/bin/lcov -o $@ --rc lcov_branch_coverage=1 \
	-r $(BUILD)/zephyr/lcov.info \
	$(TEST_PATTERNS)

$(BUILD)/zephyr/lcov_rpt: $(BUILD)/zephyr/lcov.info
	/usr/bin/genhtml --branch-coverage -q -o $@ \
	-t 'All boards and tests merged' -s $^

special_boards: $(foreach b, $(SPECIAL_BOARDS), $(BUILD)/zephyr/$(b)_rpt)

$(BUILD)/zephy/%_merged.info: $(BUILD)/zephyr/%/output/zephyr.info $(BUILD)/zephyr/all_tests.info
	/usr/bin/lcov -o $@ --rc lcov_branch_coverage=1 \
	-a $(BUILD)/zephyr/all_tests.info -a $<

$(BUILD)/zephyr/%_stenciled.info: $(BUILD)/zephyr/%/output/zephyr.info $(BUILD)/zephy/%_merged.info
	$(PLATFORM_EC)/util/lcov_stencil.py -o $@ $^

.NOTINTERMEDIATE: $(BUILD)/zephyr/%_final.info
$(BUILD)/zephyr/%_final.info: $(BUILD)/zephyr/%_stenciled.info
	/usr/bin/lcov -o $@ --rc lcov_branch_coverage=1 \
	-r $< \
	'$(THIRD_PARTY)/**' \
	'$(PLATFORM_EC)/zephyr/drivers/**' \
	'$(PLATFORM_EC)/zephyr/include/drivers/**' \
	'$(PLATFORM_EC)/zephyr/program/**' \
	'$(PLATFORM_EC)/zephyr/shim/chip/**' \
	'$(PLATFORM_EC)/zephyr/shim/chip/npcx/npcx_monitor/**' \
	'$(PLATFORM_EC)/zephyr/shim/core/**' \
	$(GENERATED_AND_SYSTEM_PATTERNS) $(TEST_PATTERNS)

.NOTINTERMEDIATE: $(BUILD)/zephyr/%_rpt
$(BUILD)/zephyr/%_rpt: $(BUILD)/zephyr/%_final.info
	/usr/bin/genhtml --branch-coverage -q -o $@ \
	-t '$* ec code only' -s $^
