# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_BROX_ISH_EC=y

# Disable sensors
CONFIG_PLATFORM_EC_MOTIONSENSE=n

# TODO(b/319165213) Disable tablet mode in the EC for now. Next, we'll need to
#   use an interrupt line from the ISH to the EC to notify of tablet mode
#   changes.
CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_TABLET_MODE_SWITCH=y
# CBI EEPROM support
CONFIG_EEPROM=y
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y
CONFIG_PLATFORM_EC_EEPROM_CBI_WP=y

CONFIG_I2C_TARGET=y
CONFIG_DSP_COMMS_LOG_LEVEL_DBG=y

CONFIG_ISR_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_WATCHDOG=n
CONFIG_USB_PDC_LOG_LEVEL_ERR=y

# Language
CONFIG_CPP=y
CONFIG_STD_CPP20=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# CONFIG_PICOLIBC=y
# CONFIG_PICOLIBC_MODULE=y
# CONFIG_PICOLIBC_USE_MODULE=y
# CONFIG_PIGWEED_MINIMAL_CPP_STDLIB=y
# CONFIG_EXTERNAL_MODULE_LIBCPP=y
