#!/bin/bash
#
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Generate version information for the EC binary
#
# Generally we only have a single version. But for some platforms we build
# from other repositories. So in that case a combined version string is
# generated from all the repositories (CROS_EC_ALL_VERSION).

get_version() {
	local dir="$1" dirty_char=""
	local -n vers="$2" dirty="$3"

	git_dir="--git-dir=${dir}/.git"
	work_tree="--work-tree=${dir}"
	if ghash=`git ${git_dir} rev-parse --short --verify HEAD \
			2>/dev/null`; then
		if gdesc=`git ${git_dir} describe --dirty --match='v*' \
				2>/dev/null`; then
			IFS="-" fields=($gdesc)
			tag="${fields[0]}"
			IFS="." vernum=($tag)
			IFS=
			numcommits=$((${vernum[2]}+${fields[1]:-0}))
			ver_major="${vernum[0]}"
			ver_branch="${vernum[1]}"
		else
			numcommits=`git ${git_dir} rev-list HEAD | wc -l`
			ver_major="v0"
			ver_branch="0"
		fi
		# avoid putting the -dirty attribute if only the timestamp
		# changed
		if [[ "$(git ${git_dir} ${work_tree} \
				diff-index --name-only HEAD)" ]]; then
			dirty_char="+"
		fi
		vbase="${ver_major}.${ver_branch}.${numcommits}-"\
"${ghash}${dirty_char}"
	else
		# Fall back to the VCSID provided by the packaging system if
		# available.
		if ghash=${VCSID##*-}; then
			vbase="1.1.9999-${ghash:0:7}"
		else
			# then ultimately fails to "no_version"
			vbase="no_version"
		fi
	fi

	vers="${BOARD}_${vbase}"
	dirty="${dirty_char}"
}

generate_version() {
	local subsystem="$1" vers="$2"

	echo "#define ${subsystem}_VERSION \"${vers}\""
	echo "#define ${subsystem}_VERSION32 \"${vers:0:31}\""
	echo
}

echo "/* This file is generated by util/getversion.sh */"

${CROS_WORKON_LOCALNAME}

get_version "." ver dirty

echo "/* Sub-fields for use in Makefile.rules and to form build info string"
echo " * in common/version.c. */"
echo "#define VERSION \"${ver}\""
echo "#define BUILDER \"${USER}@`hostname`\""
echo

if [ -n "$dirty" ]; then
    echo "/* Repo is dirty, using time of last compilation */"
    echo "#define DATE \"$(date '+%F %T')\""
else
    echo "/* Repo is clean, use the commit date of the last commit */"
    gitdate=$(git log -1 --format='%ci' HEAD | cut -d ' ' -f '1 2')
    echo "#define DATE \"${gitdate}\""
fi

echo
echo "/*"
echo " * Version strings for use by common/version.c. The '32' version is the"
echo " * same, but truncated to 31 chars (+ terminating null = 32)"
echo "*/"
generate_version CROS_EC ${ver}

if [ -n "${EXTENDED_VERSION}" ]; then
	all="${ver}"
	get_version "private-cr51" ver dirty
	generate_version "CROS_EC_CR51" "${ver}"
	all+=";cr51:${ver}"

	get_version "../../third_party/cryptoc" ver dirty
	generate_version "CROS_EC_CRYPTOC" "${ver}"
	all+=";cryptoc:${ver}"

	get_version "../../third_party/tpm2" ver dirty
	generate_version "CROS_EC_TPM2" "${ver}"
	all+=";tpm2:${ver}"

	generate_version "CROS_EC_ALL" "${all}"
else
	echo "/* Combined version string for all components */"
	generate_version "CROS_EC_ALL" "${ver}"
fi
