#! /usr/bin/python
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Find "symbols" in the form "@xxx" in a C program and generate code
# that declares and initializes those symbols.

import os
import re
import sys

print "/* This file is generated by a program */\n"

symbols = set(re.findall("@(\\w+)", sys.stdin.read()))

for s in symbols:
    print "struct object %s_symbol = { .type = SYMBOL, .u.name = \"%s\" };" \
           % (s, s)

print "\nvoid intern_builtin_symbols(void) {"

for s in symbols:
    print "  intern_builtin(&%s_symbol);" % s

print "}\n"
