# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Update the logging to be more verbose
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_SHELL_LOG_FORMAT_TIMESTAMP=y

# Disable power management
CONFIG_PM=n

# Reduce the polling rate for UART so it's responsive
CONFIG_SHELL_BACKEND_SERIAL_RX_POLL_PERIOD=100
