
PROVIDE(aes_sha_power = 0x00006f90);
PROVIDE(aes_sha_reset = 0x00006fb4);
PROVIDE(sha_is_done = 0x0000881c);
PROVIDE(sha_start = 0x000087b8);
PROVIDE(rom_log_get_ptr = 0x00000d6c);
PROVIDE(_ROM_Log_Size = 0x00000100);
PROVIDE(sha12_finalize = 0x000089dc);
PROVIDE(sha12_init = 0x00008860);
PROVIDE(sha12_update = 0x0000891c);
PROVIDE(sha35_finalize = 0x00008cbc);
PROVIDE(sha35_init = 0x00008bb4);
PROVIDE(sha35_update = 0x00008bfc);
PROVIDE(sha_final = 0x00008ef4);
PROVIDE(sha_init = 0x00008db4);
PROVIDE(sha_update = 0x00008e70);

