# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_CROS_EC=y

# SoC configuration
CONFIG_FPU=y
CONFIG_ARM_MPU=y
CONFIG_ADC=y

CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y
CONFIG_PLATFORM_EC_LID_SWITCH=y
CONFIG_PLATFORM_EC_POWER_BUTTON=y

CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_CROS_KB_RAW_NPCX=n
CONFIG_PLATFORM_EC_VBOOT=n
CONFIG_PLATFORM_EC_VBOOT_HASH=n
# Flash
CONFIG_PLATFORM_EC_PROTECTED_STORAGE_OFF=0x0
CONFIG_PLATFORM_EC_PROTECTED_STORAGE_SIZE=0x40000
CONFIG_PLATFORM_EC_WRITABLE_STORAGE_OFF=0x40000
CONFIG_PLATFORM_EC_WRITABLE_STORAGE_SIZE=0x40000
