# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp-ite board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_ITE=y

# Enable JTAG debugging of EC images
CONFIG_SOC_IT8XXX2_JTAG_DEBUG_INTERFACE=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_WATCHDOG=n
CONFIG_PLATFORM_EC_BUTTON=n
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=n
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=n

# Disable options not yet configured
