# Copyright 2022 The ChromiumOS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Rex reference-board-specific Kconfig settings.
CONFIG_BOARD_REX=y

# Keyboard
CONFIG_CROS_KB_RAW_NPCX=y

# Sensors
CONFIG_SENSOR=y
CONFIG_SENSOR_SHELL=n

# Sensor drivers
CONFIG_PLATFORM_EC_ACCELGYRO_LSM6DSO=y
