# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Link some code into RAM to improve performance.
CONFIG_SOC_IT8XXX2_SERIAL_IN_RAM=y
CONFIG_SOC_IT8XXX2_KERNEL_IN_RAM=y
CONFIG_SOC_IT8XXX2_ZEPHYR_IN_RAM=y

# CBI configuration
CONFIG_PLATFORM_EC_CBI=y
CONFIG_PLATFORM_EC_BOARD_VERSION_CBI=y

# Keyboard
CONFIG_INPUT=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_CROS_EC_KEYBOARD_INPUT=y
CONFIG_INPUT_SHELL=y
CONFIG_INPUT_EVENT_DUMP=y
CONFIG_INPUT_SHELL_KBD_MATRIX_STATE=y
