# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Link some code into RAM to improve performance.

CONFIG_SOC_IT51XXX_KERNEL_IN_RAM=y
CONFIG_SOC_IT51XXX_ZEPHYR_IN_RAM=n
CONFIG_I2C_CODE_IN_RAM=y
CONFIG_SOC_IT51XXX_ILM_SIZE_32K=y
