/* Copyright 2025 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* Private sensor interface */

#ifndef ZEPHYR_DRIVERS_FINGERPRINT_EGIS630_PRIVATE_H_
#define ZEPHYR_DRIVERS_FINGERPRINT_EGIS630_PRIVATE_H_

typedef enum {
	EGIS_API_OK = 0,
	EGIS_API_IMAGE_QUALITY_GOOD = 0,
	EGIS_API_IMAGE_QUALITY_BAD = 1,
	EGIS_API_IMAGE_QUALITY_WATER = 2,
	EGIS_API_IMAGE_QUALITY_PARTIAL = 3,
	EGIS_API_IMAGE_EMPTY = 4,
	EGIS_API_FINGER_PRESENT = 5,
	EGIS_API_FINGER_LOST = 6,
	EGIS_API_ENROLL_FINISH = 11,
	EGIS_API_ENROLL_IMAGE_OK = 12,
	EGIS_API_ENROLL_REDUNDANT_INPUT = 13,
	EGIS_API_ENROLL_LOW_QUALITY = 14,
	EGIS_API_ENROLL_LOW_COVERAGE = 15,
	EGIS_API_MATCH_MATCHED = 21,
	EGIS_API_MATCH_MATCHED_UPDATED = 22,
	EGIS_API_MATCH_MATCHED_UPDATED_FAILED = 23,
	EGIS_API_MATCH_NOT_MATCHED = 24,
	EGIS_API_MATCH_LOW_QUALITY = 25,
	EGIS_API_MATCH_LOW_COVERAGE = 26,
	EGIS_API_ERROR_GENERAL = -1,
	EGIS_API_ERROR_COMMAND_FAIL = -2,
	EGIS_API_ERROR_DEVICE_NOT_FOUND = -3,
	EGIS_API_ERROR_MEMORY = -4,
	EGIS_API_ERROR_PARAMETER = -5,
	EGIS_API_ERROR_WRONG_STATE = -6,
	EGIS_API_ERROR_IO_SPI = -7,
	EGIS_API_ERROR_SENSOR_GENERAL = -11,
	EGIS_API_ERROR_SENSOR_SENSING_MDOE_CALIBRATION = -12,
	EGIS_API_ERROR_SENSOR_DETECT_MDOE_CALIBRATION = -13,
	EGIS_API_ERROR_SENSOR_NEED_RESET = -15,
	EGIS_API_ERROR_SENSOR_OCP_DETECT = -16,
	EGIS_API_ERROR_FINGER_UNSTABLE = -17,
	EGIS_API_ERROR_MATCHER_LIB_FAIL = -18,
	EGIS_API_ERROR_EMFP_LIB_FAIL = -19,
	EGIS_API_ERROR = -20,
} egis_api_return_t;

#endif /* ZEPHYR_DRIVERS_FINGERPRINT_EGIS630_PRIVATE_H_ */
