/* Copyright 2018 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#include <compile_time_macros.h>
#include <stdint.h>

#include "bootblock.h"

/* This file is auto-generated by gen_emmc_transfer_data. */
#include "bootblock_data.h"

BUILD_ASSERT(sizeof(bootblock_raw_data) > BOOTBLOCK_DATA_MIN_SIZE);

/* Returns the bootblock data */
const uint8_t *bootblock_get_data(void)
{
	return bootblock_raw_data;
}

/* Returns the bootblock data size */
int bootblock_get_size(void)
{
	return sizeof(bootblock_raw_data);
}
