#![no_std]
#![crate_type = "staticlib"]
#![allow(non_camel_case_types)]

use core::cmp::min;
use core::mem::size_of;
use core::sync::atomic::AtomicBool;
use core::sync::atomic::Ordering;

use common::generated::*;
use common::raw::*;
use common::*;

static HOOK_LIST: &[StaticArray<hook_data>] = unsafe {
    &[
        StaticArray(&__hooks_init, &__hooks_init_end),
        StaticArray(&__hooks_pre_freq_change, &__hooks_pre_freq_change_end),
        StaticArray(&__hooks_freq_change, &__hooks_freq_change_end),
        StaticArray(&__hooks_sysjump, &__hooks_sysjump_end),
        StaticArray(&__hooks_chipset_pre_init, &__hooks_chipset_pre_init_end),
        StaticArray(&__hooks_chipset_startup, &__hooks_chipset_startup_end),
        StaticArray(&__hooks_chipset_resume, &__hooks_chipset_resume_end),
        StaticArray(&__hooks_chipset_suspend, &__hooks_chipset_suspend_end),
        StaticArray(&__hooks_chipset_shutdown, &__hooks_chipset_shutdown_end),
        StaticArray(&__hooks_chipset_reset, &__hooks_chipset_reset_end),
        StaticArray(&__hooks_ac_change, &__hooks_ac_change_end),
        StaticArray(&__hooks_lid_change, &__hooks_lid_change_end),
        StaticArray(&__hooks_tablet_mode_change, &__hooks_tablet_mode_change_end),
        StaticArray(
            &__hooks_base_attached_change,
            &__hooks_base_attached_change_end,
        ),
        StaticArray(&__hooks_pwrbtn_change, &__hooks_pwrbtn_change_end),
        StaticArray(&__hooks_battery_soc_change, &__hooks_battery_soc_change_end),
        #[cfg(feature = "CONFIG_CASE_CLOSED_DEBUG_V1")]
        StaticArray(&__hooks_ccd_change, &__hooks_ccd_change_end),
        #[cfg(feature = "CONFIG_USB_SUSPEND")]
        StaticArray(&__hooks_usb_change, &__hooks_usb_change_end),
        StaticArray(&__hooks_tick, &__hooks_tick_end),
        StaticArray(&__hooks_second, &__hooks_second_end),
        StaticArray(&__hooks_usb_pd_disconnect, &__hooks_usb_pd_disconnect_end),
    ]
};

static mut DEFERRED_UNTIL: StaticMutArray<u64> =
    unsafe { StaticMutArray(&mut __deferred_until, &mut __deferred_until_end) };
static mut DEFERRED_FUNCS: StaticArray<deferred_data> =
    unsafe { StaticArray(&__deferred_funcs, &__deferred_funcs_end) };

static HOOK_TASK_STARTED: AtomicBool = AtomicBool::new(false);
static DEFER_NEW_CALL: AtomicBool = AtomicBool::new(false);

#[no_mangle]
pub fn hook_notify(type_: hook_type) {
    if type_ as usize >= HOOK_LIST.len() {
        return;
    }

    // Safe because the HOOK_LIST was constructed using pointers generated by the linker.
    let hooks = unsafe { HOOK_LIST[type_ as usize].as_slice() };

    let mut count = 0;
    let mut last_priority = (HOOK_PRIO_FIRST - 1) as c_int;
    // Call all the hooks in priority order.
    while count < hooks.len() {
        // Find the lowest remaining priority
        let mut min_priority = (HOOK_PRIO_LAST + 1) as c_int;
        for hook in hooks.iter() {
            if hook.priority < min_priority && hook.priority > last_priority {
                min_priority = hook.priority
            }
        }
        last_priority = min_priority;

        // Call all the hooks with that priority
        for hook in hooks.iter() {
            if hook.priority == min_priority {
                count += 1;
                if let Some(routine) = hook.routine {
                    // The hook's routine is always unsafe to call.
                    unsafe {
                        routine();
                    }
                }
            }
        }
    }
}

#[no_mangle]
pub unsafe extern "C" fn hook_call_deferred(data: *const deferred_data, us: i32) -> c_int {
    let i = isize::wrapping_sub(data as _, __deferred_funcs.as_ptr() as _)
        / size_of::<deferred_data>() as isize;

    if data < __deferred_funcs.as_ptr() || data >= __deferred_funcs_end.as_ptr() {
        return EC_ERROR_INVAL as c_int;
    }

    let p: &mut u64 = __deferred_until.get_unchecked_mut(i as usize);
    if us < 0 {
        // Cancel
        *p = 0;
    } else {
        let future = EcInstant::now();
        // Set Alarm
        *p = (future + EcDuration(us as u64)).as_micros();
        // Flag that hook_call_deferred() has been called.  If the hook task is already active, this
        // will allow it to go through the loop one more time before sleeping.
        DEFER_NEW_CALL.store(true, Ordering::SeqCst);

        if HOOK_TASK_STARTED.load(Ordering::SeqCst) {
            task_set_event(TASK_ID_HOOKS as task_id_t, TASK_EVENT_WAKE, 0);
        }
    }

    EC_SUCCESS as c_int
}

// Declares a mutable static variable and a reference on the stack to it. May not be used for
// functions that need to be reentrant and is therefore unsafe.
macro_rules! unsafe_static_mut {
    (static mut $id:ident: $t:ty = $init:expr) => {
        #[allow(non_upper_case_globals)]
        let $id = unsafe {
            static mut $id: $t = $init;
            &mut $id
        };
    };
}

#[no_mangle]
pub extern "C" fn hook_task(_u: c_void) -> ! {
    const HOOK_TICK_INTERVAL: EcDuration = EcDuration(HOOK_TICK_INTERVAL_MS as u64 * 1000);
    unsafe_static_mut!(static mut last_second: EcInstant = EcInstant(0));
    unsafe_static_mut!(static mut last_tick: EcInstant = EcInstant(0));
    let mut first = true;

    str_put(CC_SYSTEM, "rust hooks started\n");

    HOOK_TASK_STARTED.store(true, Ordering::SeqCst);

    // Call HOOK_INIT hooks
    hook_notify(HOOK_INIT);
    // Now, enable the rest of the tasks.
    unsafe {
        task_enable_all_tasks();
    }

    loop {
        let t = EcInstant::now();
        let mut next = EcDuration(0);

        for (deferred_until, deferred_func) in unsafe {
            DEFERRED_UNTIL
                .as_mut_slice()
                .iter_mut()
                .zip(DEFERRED_FUNCS.as_slice().iter())
        } {
            if *deferred_until != 0 && EcInstant(*deferred_until) < t {
                // Call deferred function.  Clear timer first, so it can request itself be called
                // later.
                *deferred_until = 0;
                if let Some(routine) = deferred_func.routine {
                    // The hook's routine is always unsafe to call.
                    unsafe {
                        routine();
                    }
                }
            }
        }

        if first || t.duration_since_elapsed(*last_tick, HOOK_TICK_INTERVAL) {
            hook_notify(HOOK_TICK);
            *last_tick = t;
        }

        if first || t.duration_since_elapsed(*last_second, common::SECOND) {
            hook_notify(HOOK_SECOND);
            *last_second = t;
        }
        first = false;

        // Calculate when next tick needs to occur
        let t = EcInstant::now();
        if let Some(next_tick) = (*last_tick + HOOK_TICK_INTERVAL).checked_duration_since(t) {
            next = next_tick;
        }

        // Wake earlier if needed by a deferred routine
        DEFER_NEW_CALL.store(false, Ordering::SeqCst);

        for deferred_until in unsafe { DEFERRED_UNTIL.as_slice().iter() } {
            if next.zero() {
                break;
            }
            if *deferred_until == 0 {
                continue;
            }

            let future_duration = EcInstant(*deferred_until)
                .checked_duration_since(t)
                .unwrap_or(EcDuration(0));
            next = min(future_duration, next)
        }

        // If nothing is immediately pending, and hook_call_deferred() hasn't been called since we
        // started calculating next, sleep until the next event.
        if !next.zero() && !DEFER_NEW_CALL.load(Ordering::SeqCst) {
            unsafe { task_wait_event(next.as_micros() as i32) };
        }
    }
}
