/* Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 *
 * TI bq24770 battery charger driver.
 */

#ifndef __CROS_EC_CHARGER_BQ24770_H
#define __CROS_EC_CHARGER_BQ24770_H

/* I2C address */
#define BQ24770_ADDR 0x12

/* Chip specific commands */
#define BQ24770_CHARGE_OPTION0          0x12
#define BQ24770_CHARGE_OPTION1          0x3b
#define BQ24770_CHARGE_OPTION2          0x38
#define BQ24770_PROCHOT_OPTION0         0x3c
#define BQ24770_PROCHOT_OPTION1         0x3d
#define BQ24770_MANUFACTURER_ID         0xfe
#define BQ24770_DEVICE_ADDRESS          0xff
#define BQ24770_CHARGE_CURRENT          0x14
#define BQ24770_MAX_CHARGE_VOLTAGE      0x15
#define BQ24770_MIN_SYSTEM_VOLTAGE      0x3e
#define BQ24770_INPUT_CURRENT           0x3f

/* Option bits */
#define OPTION0_LOW_POWER_MODE_EN       (1 << 15)
#define OPTION0_IDPM_AUTO_DISABLE       (1 << 12)
#define OPTION0_ACOC_SETTING            (1 << 7)
#define OPTION0_LSFET_OCP_THRESHOLD     (1 << 6)
#define OPTION0_LEARN_ENABLE            (1 << 5)
#define OPTION0_CHARGE_INHIBIT          (1 << 0)
#define OPTION1_AUTO_WAKEUP_EN          (1 << 0)
#define OPTION2_EN_EXTILIM              (1 << 7)

/* prochot option 0 bit 15..11 ICRIT Comparator Threshold */
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_MASK (31 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_110_PERCENTAGE (1 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_115_PERCENTAGE (2 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_120_PERCENTAGE (3 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_125_PERCENTAGE (4 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_130_PERCENTAGE (5 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_135_PERCENTAGE (6 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_140_PERCENTAGE (7 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_145_PERCENTAGE (8 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_150_PERCENTAGE (9 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_155_PERCENTAGE (10 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_160_PERCENTAGE (11 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_165_PERCENTAGE (12 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_170_PERCENTAGE (13 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_175_PERCENTAGE (14 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_180_PERCENTAGE (15 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_185_PERCENTAGE (16 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_190_PERCENTAGE (17 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_195_PERCENTAGE (18 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_200_PERCENTAGE (19 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_205_PERCENTAGE (20 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_210_PERCENTAGE (21 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_215_PERCENTAGE (22 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_220_PERCENTAGE (23 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_225_PERCENTAGE (24 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_230_PERCENTAGE (25 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_250_PERCENTAGE (26 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_300_PERCENTAGE (27 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_350_PERCENTAGE (28 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_400_PERCENTAGE (29 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_450_PERCENTAGE (30 << 11)
#define PROCHOT_OPTION0_ICRIT_COMPARATOR_THRESHOLD_OUT_OF_RANGE (31 << 11)

/* prochot option 0 bit 7..6 VSYS Comparator Threshold */
#define PROCHOT_OPTION0_VSYS_COMPARATOR_THRESHOLD_MASK (3 << 6)
#define PROCHOT_OPTION0_VSYS_COMPARATOR_THRESHOLD_2P85_V (0 << 6)
#define PROCHOT_OPTION0_VSYS_COMPARATOR_THRESHOLD_3P1_V  (1 << 6)
#define PROCHOT_OPTION0_VSYS_COMPARATOR_THRESHOLD_3P35_V (2 << 6)
#define PROCHOT_OPTION0_VSYS_COMPARATOR_THRESHOLD_3P6_V  (3 << 6)

/* prochot option 0 bit 5 PROCHOT Plus extension enable */
#define PROCHOT_OPTION0_PULSE_EXTENSION_ENABLE (1 << 5)

/* prochot option 0 bit 4..3 PROCHOT Pluse Width */
#define PROCHOT_OPTION0_PULSE_WIDTH_MASK   (3 << 3)
#define PROCHOT_OPTION0_PULSE_WIDTH_100_US (0 << 3)
#define PROCHOT_OPTION0_PULSE_WIDTH_1_MS   (1 << 3)
#define PROCHOT_OPTION0_PULSE_WIDTH_12_MS  (2 << 3)
#define PROCHOT_OPTION0_PULSE_WIDTH_6_MS   (3 << 3)

/* prochot option 0 bit 2 PROCHOT Host Clear */
#define PROCHOT_OPTION0_HOST_CLEAR_IDLE (1 << 2)

/* prochot option 0 bit 1 INOM Comparator Deglitch Time */
#define PROCHOT_OPTION0_INOM_COMPARATOR_DEGLITCH_50_MS (1 << 1)

/* prochot option 1 bit 15..10 IDCHG Comparator Threshold */
#define PROCHOT_OPTION1_IDCHG_COMPARATOR_THRESHOLD_MASK (63 << 10)
#define PROCHOT_OPTION1_IDCHG_COMPARATOR_THRESHOLD_4096_MA (8 << 10)

/* prochot option 1 bit 9..8 IDCHG Comparator Deglitch Time */
#define PROCHOT_OPTION1_IDCHG_COMPARATOR_DEGLITCH_TIME_MASK (3 << 8)
#define PROCHOT_OPTION1_IDCHG_COMPARATOR_DEGLITCH_TIME_1P6_MS (0 << 8)

/* prochot option 1 bit 6..0 PROCHOT envelop selector */
#define PROCHOT_OPTION1_PROCHOT_ENVELOP_SELECTOR_MASK 127
#define ENVELOP_SELECTOR_INDEPENDENT_COMPARATOR_ENABLE (1 << 6)
#define ENVELOP_SELECTOR_ICRIT_ENABLE   (1 << 5)
#define ENVELOP_SELECTOR_INOM_ENABLE    (1 << 4)
#define ENVELOP_SELECTOR_IDCHG_ENABLE   (1 << 3)
#define ENVELOP_SELECTOR_VSYS_ENABLE    (1 << 2)
#define ENVELOP_SELECTOR_BATPRES_ENABLE (1 << 1)
#define ENVELOP_SELECTOR_ACOK_ENABLE    (1 << 0)



/* ChargeCurrent Register - 0x14 (mA) */
#define CHARGE_I_OFF                    0
#define CHARGE_I_MIN                    128
#define CHARGE_I_MAX                    8128
#define CHARGE_I_STEP                   64

/* MaxChargeVoltage Register - 0x15 (mV) */
#define CHARGE_V_MIN                    1024
#define CHARGE_V_MAX                    19200
#define CHARGE_V_STEP                   16

/* InputCurrent Register - 0x3f (mA) */
#define INPUT_I_MIN                    128
#define INPUT_I_MAX                    8128
#define INPUT_I_STEP                   64

#endif /* __CROS_EC_CHARGER_BQ24770_H */
