# kb project config

# Cros EC configuration
CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Disable undef features
CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
CONFIG_PLATFORM_EC_CBI=n
CONFIG_PLATFORM_EC_CBI_GPIO=n
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
CONFIG_PLATFORM_EC_VSTORE=n
CONFIG_PLATFORM_EC_VBOOT_HASH=n
CONFIG_PLATFORM_EC_SWITCH=n
CONFIG_AP=n

# Save flash
CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_TAB_AUTOCOMPLETION=n
CONFIG_SHELL_HELP=n
CONFIG_PLATFORM_EC_CONSOLE_CHANNEL=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_MD=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_RW=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_CRASH=n
CONFIG_PLATFORM_EC_HIBERNATE_WAKE_PINS=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_GETTIME=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_MEM=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_SLEEPMASK=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_SLEEPMASK_SET=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_SHMEM=n

# Peripherials
CONFIG_BBRAM=y
CONFIG_BBRAM_SHELL=y
CONFIG_COUNTER=y
CONFIG_WATCHDOG=y

# Power management
CONFIG_PM=y

CONFIG_HWINFO=y