# kb project config

# Cros EC configuration
CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Disable undef features
CONFIG_AP=n
CONFIG_PLATFORM_EC_BACKLIGHT_LID=n
CONFIG_PLATFORM_EC_CBI=n
CONFIG_PLATFORM_EC_CBI_GPIO=n
CONFIG_PLATFORM_EC_CONSOLE_CMD_SLEEPMASK=n
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
CONFIG_PLATFORM_EC_VBOOT_HASH=n
CONFIG_PLATFORM_EC_SWITCH=n

# KB
CONFIG_PLATFORM_EC_KEYBOARD_PROTOCOL_8042=n
CONFIG_PLATFORM_EC_KEYBOARD_VIVALDI=n

# Peripherials
CONFIG_BBRAM=y
CONFIG_COUNTER=y
CONFIG_WATCHDOG=y

# Power management
CONFIG_PM=y

CONFIG_HWINFO=y