
config HAVE_ALS_AL3010
	bool
	select ALS
	select ALS_AL3010

config HAVE_ALS_BH1730
	bool
	select ALS
	select ALS_BH1730

config HAVE_ALS_ISL29035
	bool
	select ALS
	select ALS_ISL29035

config HAVE_ALS_OPT3001
	bool
	select ALS
	select ALS_OPT3001

config HAVE_ALS_SI114X
	bool
	select ALS
	select ALS_SI114X__yn

config HAVE_ALS_TCS3400
	bool
	select ALS
	select ALS_TCS3400

#

config ALS
	bool "ALS support"

if ALS

menu "ALS Chips"

config ALS_AL3010
	bool "AL3010"

config ALS_BH1730
	bool "BH1730"

config ALS_BH1730_LUXTH_PARAMS
	bool "Use board specific lux calculation"
	depends on ALS_BH1730
	help
	  If defined, BH1730 uses board specific lux calculation formula parameters.
	  If not defined, BH1730 uses default parameters to calculate lux.

config ALS_ISL29035
	bool "Enable ISL29035 support"

config ALS_OPT3001
	bool "OPT3001"

config ALS_SI114X__yn
	bool "Select ALS_SI114X"
config ALS_SI114X
	hex "Define the exact model ID present on the board: SI1141 = 41, SI1142 = 42"
	range 0x00 0xff
	default 0x40 if BOARD_EVE
	depends on ALS_SI114X__yn

if ALS_SI114X

config ALS_SI114X_CHECK_REVISION
	bool "Check if the device revision is supported"

config ALS_SI114X_POLLING
	bool "Enable Si114x to operate in polling mode"
	help
	  Enable Si114x to operate in polling mode. This config is used in conjunction
	  with CONFIG_ALS_SI114X_INT_EVENT. When polling is enabled, the read is
	  initiated in the same manner as when interrupts are used, but the event which
	  triggers the irq_handler is generated by deferred call using a fixed delay.

endif # ALS_SI114X

config ALS_TCS3400
	bool "Define to include the clear channel driver for the tcs3400 light sensor"

if ALS_TCS3400

config TCS_USE_LUX_TABLE
	bool "TCS_USE_LUX_TABLE"
	help
	  Define to use atime tables in anti-saturation algos in the tcs3400 driver.
	  Defining this for a board makes the anti-saturation algorithm much more
	  efficient, but requires the board to have it's lens cover scale and k_channel
	  scales to be determined.  Define this for a board once it's added its
	  cover_scale and k_channel scale factors.

config ALS_TCS3400_EMULATED_IRQ_EVENT
	bool "Enable tcs3400 to operate without interrupt pin"
	help
	  Enable tcs3400 to operate without interrupt pin. This config is used in
	  conjunction with CONFIG_ALS_TCS3400_INT_EVENT. When this option is enabled,
	  the read is initiated in the same manner as when interrupts are used, but the
	  event which triggers the irq_handler is generated by deferred call.

endif # ALS_TCS3400

#endchoice # ALS chip

config ALS_LIGHTBAR_DIMMING
	bool "Define which ALS sensor is used for dimming the lightbar when dark"

endmenu # "ALS Chips"

endif # ALS


