# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp-npcx board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_NPCX=y

# Enable AP over eSPI
CONFIG_ESPI=y

CONFIG_AP=y

#Limit minimum power to Boot Without Battery. Later, to relook this values
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON_WITH_BATT=15000
CONFIG_PLATFORM_EC_CHARGER_MIN_POWER_MW_FOR_POWER_ON=65000

#PPM Enable (Required for AP mode entry of TBT/USB4).
#Need to cherry pick other dependent CLs.
CONFIG_UCSI_PPM=y
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
CONFIG_UCSI_PPM_EC_MODE_ENTRY=y
CONFIG_UCSI_PPM_LOG_LEVEL_DBG=y
CONFIG_UCSI_PPM_CONSOLE=y
