# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# ocelotrvp-npcx board-specific Kconfig settings.

CONFIG_BOARD_OCELOTRVP_NPCX=y

CONFIG_PLATFORM_EC_HIBERNATE_PSL=y

#PPM Enable (Required for AP mode entry of TBT/USB4).
#Need to cherry pick other dependent CLs.
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y
CONFIG_UCSI_PPM_EC_MODE_ENTRY=y
CONFIG_UCSI_PPM_LOG_LEVEL_DBG=y
CONFIG_UCSI_PPM_CONSOLE=y

