# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ADLRVP_MCHP=y
CONFIG_CROS_FLASH_XEC=y
CONFIG_CROS_SYSTEM_XEC=y

# Not need for MCHP chip
CONFIG_SYSCON=n
# Keyboard doesn't support KEYPAD - 13 Columns
CONFIG_PLATFORM_EC_KEYBOARD_KEYPAD=n

# Keyboard
CONFIG_CROS_KB_RAW_XEC=y

# For MCHP ESPI Drivers
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y
CONFIG_ESPI_PERIPHERAL_XEC_EMI0=y
CONFIG_ESPI_PERIPHERAL_ACPI_EC_IBF_EVT_DATA=y
CONFIG_ESPI_PERIPHERAL_KBC_OBE_CBK=y
CONFIG_ESPI_PERIPHERAL_KBC_IBF_EVT_DATA=y

# debug purpose - configure both as using JTAG i/f
# WATCHDOG configuration
#CONFIG_WATCHDOG=n
#CONFIG_WDT_XEC=n
# Error log, debug purpose
## CONFIG_LOG=y
## CONFIG_THREAD_NAME=y

# USB-C and PD
# mchp_0425
# CONFIG_PLATFORM_EC_USB_PD_PORT_MAX_COUNT=2

# TODO
# Fan
CONFIG_PLATFORM_EC_FAN=n
CONFIG_TACH_NPCX=n

# RTC
CONFIG_PLATFORM_EC_RTC=n

# PWM
CONFIG_PWM=n
CONFIG_PWM_SHELL=n

# Invoke SoC Python script to create zephyr.mchp.bin which
# is zephyr.bin processed for Boot-ROM loading.
CONFIG_MCHP_MEC_HEADER=y
CONFIG_MCHP_MEC_HEADER_FLASH_SIZE_256K=y

####################
# TODO
# mchp_0425
#### INTEL
# Host command
CONFIG_PLATFORM_EC_HOSTCMD_AP_RESET=n

# Power Sequencing
CONFIG_PLATFORM_EC_THROTTLE_AP=n

# Sensors
CONFIG_SENSOR=n
CONFIG_SENSOR_SHELL=n

#### ADL
# CBI
CONFIG_EEPROM=n
CONFIG_EEPROM_AT24=n
CONFIG_EEPROM_SHELL=n
CONFIG_PLATFORM_EC_CBI_EEPROM=n

# LED
CONFIG_PLATFORM_EC_LED_COMMON=n

# Temperature sensors
CONFIG_PLATFORM_EC_TEMP_SENSOR=n
CONFIG_PLATFORM_EC_THERMISTOR=n
CONFIG_PLATFORM_EC_TEMP_SENSOR_POWER=n

# 7-Segment Display
CONFIG_PLATFORM_EC_MAX695X_SEVEN_SEGMENT_DISPLAY=n

#### MCHP
# Charger
CONFIG_PLATFORM_EC_DEDICATED_CHARGE_PORT=n
