# Cros EC
CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y

# Shell features
CONFIG_KERNEL_SHELL=y
CONFIG_SHELL_HELP=y
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_HISTORY=y

# Bring up options
CONFIG_PLATFORM_EC_SYSTEM_UNLOCKED=y

# Keyboard
# TODO: enable this for VOLUME_BUTTONS,but wormdingler does not have keyboard
#       we should fix the unsatisfied dependencies in Kconfig.keyboard later
#CONFIG_PLATFORM_EC_KEYBOARD=y

# Button and switch
CONFIG_PLATFORM_EC_HOSTCMD=y
CONFIG_PLATFORM_EC_LID_SWITCH=y
CONFIG_PLATFORM_EC_POWER_BUTTON=y
CONFIG_PLATFORM_EC_VOLUME_BUTTONS=y

# I2C
CONFIG_I2C=y
CONFIG_PLATFORM_EC_I2C=y

# Battery
CONFIG_PLATFORM_EC_BATTERY=y
CONFIG_PLATFORM_EC_BATTERY_SMART=y
CONFIG_PLATFORM_EC_BATTERY_FUEL_GAUGE=y
CONFIG_PLATFORM_EC_BATTERY_CUT_OFF=y
CONFIG_PLATFORM_EC_BATTERY_PRESENT_GPIO=y
CONFIG_PLATFORM_EC_EXTPOWER_GPIO=y
# disable this for build pass, enable this later
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_NOT_PRESENT=y
CONFIG_PLATFORM_EC_CHARGER=n
CONFIG_PLATFORM_EC_USBC=n

# must undefine to build pass
# difine this until enable this functions
CONFIG_PLATFORM_EC_VBOOT_EFS2=n
# Power sequencing
CONFIG_AP=n
# Keyboard
CONFIG_PLATFORM_EC_KEYBOARD=n
CONFIG_CROS_KB_RAW_NPCX=n


# must define to build pass
CONFIG_SOC_NPCX7M7FC=y
CONFIG_SOC_SERIES_NPCX7=y
CONFIG_SYSCON=y

