/* Copyright 2023 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef __CROS_EC_EC_CMD_API_H
#define __CROS_EC_EC_CMD_API_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * This file consists of 3 sections for different styles of EC API
 * functions that:
 *
 * 1. need to be implemented explicitly.
 * 2. can be generated with the help of macros.
 * 3. are auto-generated by host-command/api-gen.sh.
 *
 * Note:
 *
 * A CROS_EC_COMMAND_INFO macro must be defined before including this
 * file to a data type holding the context info identifying the EC.
 *
 * A CROS_EC_COMMAND macro must be defined before including this file
 * with the following signature:
 *
 * int CROS_EC_COMMAND(CROS_EC_COMMAND_INFO *h,
 *		       int command, int version,
 *		       const void *outdata, int outsize,
 *		       void *indata, int insize)
 */

/*
 * Section 1: Functions that need to be implemented explicitly because
 * they do not adhere to simple naming that would permit
 * auto-generation.
 */

static inline int ec_cmd_get_cros_board_info(CROS_EC_COMMAND_INFO *h,
					     const struct ec_params_get_cbi *p,
					     uint32_t *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_CROS_BOARD_INFO, 0, p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int
ec_cmd_usb_pd_get_amode(CROS_EC_COMMAND_INFO *h,
			const struct ec_params_usb_pd_get_mode_request *p,
			struct ec_params_usb_pd_get_mode_response *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_GET_AMODE, 0, p, sizeof(*p), r,
			       sizeof(*r));
}

static inline int
ec_cmd_usb_pd_set_amode(CROS_EC_COMMAND_INFO *h,
			const struct ec_params_usb_pd_set_mode_request *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_SET_AMODE, 0, p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_get_sku_id(CROS_EC_COMMAND_INFO *h,
				    struct ec_sku_id_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_SKU_ID, 0, NULL, 0, r, sizeof(*r));
}

static inline int ec_cmd_set_sku_id(CROS_EC_COMMAND_INFO *h,
				    const struct ec_sku_id_info *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_SET_SKU_ID, 0, p, sizeof(*p), NULL, 0);
}

static inline int ec_cmd_thermal_get_threshold_v1(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_thermal_get_threshold_v1 *p,
	struct ec_thermal_config *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_THERMAL_GET_THRESHOLD, 1, p,
			       sizeof(*p), r, sizeof(*r));
}

/*
 * Section 2: Functions that can be generated with the help of template
 * macros.
 */

/*
 * Template for EC CMD API function that takes a param and returns a
 * response.
 */
#define _CROS_EC_F_PR(_cmd, _v, _fn, _in, _out)                               \
	static inline int ec_cmd_##_fn(CROS_EC_COMMAND_INFO *h,               \
				       const struct ec_params_##_in *p,       \
				       struct ec_response_##_out *r)          \
	{                                                                     \
		return CROS_EC_COMMAND(h, EC_CMD_##_cmd, (_v), p, sizeof(*p), \
				       r, sizeof(*r));                        \
	}

/*
 * Template for EC CMD API function that takes a param but does not
 * return a response.
 */
#define _CROS_EC_F_P(_cmd, _v, _fn, _in)                                      \
	static inline int ec_cmd_##_fn(CROS_EC_COMMAND_INFO *h,               \
				       const struct ec_params_##_in *p)       \
	{                                                                     \
		return CROS_EC_COMMAND(h, EC_CMD_##_cmd, (_v), p, sizeof(*p), \
				       NULL, 0);                              \
	}

/*
 * Template for EC CMD API function that does not take a param but does
 * return a response.
 */
#define _CROS_EC_F_R(_cmd, _v, _fn, _out)                                  \
	static inline int ec_cmd_##_fn(CROS_EC_COMMAND_INFO *h,            \
				       struct ec_response_##_out *r)       \
	{                                                                  \
		return CROS_EC_COMMAND(h, EC_CMD_##_cmd, (_v), NULL, 0, r, \
				       sizeof(*r));                        \
	}

_CROS_EC_F_R(HOST_EVENT_GET_B, 0, host_event_get_b, host_event_mask)
_CROS_EC_F_P(HOST_EVENT_CLEAR_B, 0, host_event_clear_b, host_event_mask)
_CROS_EC_F_P(BATTERY_CUT_OFF, 1, battery_cut_off_v1, battery_cutoff)
_CROS_EC_F_PR(MOTION_SENSE_CMD, 2, motion_sense_cmd_v2, motion_sense,
	      motion_sense)
_CROS_EC_F_PR(USB_PD_CONTROL, 2, usb_pd_control_v2, usb_pd_control,
	      usb_pd_control_v2)
_CROS_EC_F_PR(GET_CMD_VERSIONS, 1, get_cmd_versions_v1, get_cmd_versions_v1,
	      get_cmd_versions)
_CROS_EC_F_PR(FLASH_PROTECT, 1, flash_protect_v1, flash_protect, flash_protect)
_CROS_EC_F_PR(FLASH_REGION_INFO, 1, flash_region_info_v1, flash_region_info,
	      flash_region_info)
_CROS_EC_F_R(RTC_GET_VALUE, 0, rtc_get_value, rtc)
_CROS_EC_F_R(GET_BOARD_VERSION, 0, get_board_version, board_version)
_CROS_EC_F_R(GET_UPTIME_INFO, 0, get_uptime_info, uptime_info)
_CROS_EC_F_P(OVERRIDE_DEDICATED_CHARGER_LIMIT, 0,
	     override_dedicated_charger_limit, dedicated_charger_limit)
_CROS_EC_F_R(GET_KEYBD_CONFIG, 0, get_keybd_config, keybd_config)
_CROS_EC_F_P(ADD_ENTROPY, 0, add_entropy, rollback_add_entropy)
_CROS_EC_F_PR(GSV_PAUSE_IN_S5, 0, gsv_pause_in_s5, get_set_value, get_set_value)
_CROS_EC_F_PR(LED_CONTROL, 1, led_control_v1, led_control, led_control)
_CROS_EC_F_R(PD_HOST_EVENT_STATUS, 0, pd_host_event_status, host_event_status)

/*
 * Section 3: Functions that are generated by
 * util/host-command/api-gen.sh. Do not edit this section directly;
 * instead replace with the output of util/host-command/api-gen.sh.
 */

/* clang-format off */

static inline int ec_cmd_adc_read(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_adc_read *p,
	struct ec_response_adc_read *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_ADC_READ, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_battery_vendor_param(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_battery_vendor_param *p,
	struct ec_response_battery_vendor_param *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_BATTERY_VENDOR_PARAM, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_cec_get(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_cec_get *p,
	struct ec_response_cec_get *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_CEC_GET, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_charge_state(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_charge_state *p,
	struct ec_response_charge_state *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_CHARGE_STATE, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_chargesplash(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_chargesplash *p,
	struct ec_response_chargesplash *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_CHARGESPLASH, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_device_event(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_device_event *p,
	struct ec_response_device_event *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_DEVICE_EVENT, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_fp_mode(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_fp_mode *p,
	struct ec_response_fp_mode *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_FP_MODE, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_get_cmd_versions(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_get_cmd_versions *p,
	struct ec_response_get_cmd_versions *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_CMD_VERSIONS, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_get_pd_port_caps(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_get_pd_port_caps *p,
	struct ec_response_get_pd_port_caps *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_PD_PORT_CAPS, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_hello(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_hello *p,
	struct ec_response_hello *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_HELLO, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_hibernation_delay(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_hibernation_delay *p,
	struct ec_response_hibernation_delay *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_HIBERNATION_DELAY, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_host_event(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_host_event *p,
	struct ec_response_host_event *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_HOST_EVENT, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_i2c_control(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_i2c_control *p,
	struct ec_response_i2c_control *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_I2C_CONTROL, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_locate_chip(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_locate_chip *p,
	struct ec_response_locate_chip *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_LOCATE_CHIP, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_pd_chip_info(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pd_chip_info *p,
	struct ec_response_pd_chip_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_PD_CHIP_INFO, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_pwm_get_duty(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pwm_get_duty *p,
	struct ec_response_pwm_get_duty *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_PWM_GET_DUTY, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_regulator_get_voltage(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_regulator_get_voltage *p,
	struct ec_response_regulator_get_voltage *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_REGULATOR_GET_VOLTAGE, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_regulator_is_enabled(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_regulator_is_enabled *p,
	struct ec_response_regulator_is_enabled *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_REGULATOR_IS_ENABLED, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_rgbkbd(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_rgbkbd *p,
	struct ec_response_rgbkbd *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_RGBKBD, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_switch_enable_wireless_v1(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_switch_enable_wireless_v1 *p,
	struct ec_response_switch_enable_wireless_v1 *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_SWITCH_ENABLE_WIRELESS, 1,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_temp_sensor_get_info(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_temp_sensor_get_info *p,
	struct ec_response_temp_sensor_get_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_TEMP_SENSOR_GET_INFO, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_thermal_get_threshold(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_thermal_get_threshold *p,
	struct ec_response_thermal_get_threshold *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_THERMAL_GET_THRESHOLD, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_tmp006_get_raw(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_tmp006_get_raw *p,
	struct ec_response_tmp006_get_raw *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_TMP006_GET_RAW, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_typec_status(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_typec_status *p,
	struct ec_response_typec_status *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_TYPEC_STATUS, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_control(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_pd_control *p,
	struct ec_response_usb_pd_control *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_CONTROL, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_mux_info(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_pd_mux_info *p,
	struct ec_response_usb_pd_mux_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_MUX_INFO, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_power_info(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_pd_power_info *p,
	struct ec_response_usb_pd_power_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_POWER_INFO, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_vboot_hash(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_vboot_hash *p,
	struct ec_response_vboot_hash *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_VBOOT_HASH, 0,
			       p, sizeof(*p),
			       r, sizeof(*r));
}

static inline int ec_cmd_button(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_button *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_BUTTON, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_cec_set(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_cec_set *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_CEC_SET, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_config_power_button(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_config_power_button *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_CONFIG_POWER_BUTTON, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_efs_verify(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_efs_verify *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_EFS_VERIFY, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_external_power_limit_v1(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_external_power_limit_v1 *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_EXTERNAL_POWER_LIMIT, 1,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_flash_erase(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_flash_erase *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_FLASH_ERASE, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_force_lid_open(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_force_lid_open *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_FORCE_LID_OPEN, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_fp_seed(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_fp_seed *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_FP_SEED, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_gpio_set(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_gpio_set *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_GPIO_SET, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_hang_detect(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_hang_detect *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_HANG_DETECT, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_mkbp_simulate_key(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_mkbp_simulate_key *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_MKBP_SIMULATE_KEY, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_pd_control(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pd_control *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_PD_CONTROL, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_pd_write_log_entry(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pd_write_log_entry *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_PD_WRITE_LOG_ENTRY, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_pstore_write(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pstore_write *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_PSTORE_WRITE, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_pwm_set_duty(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pwm_set_duty *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_PWM_SET_DUTY, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_pwm_set_fan_duty_v0(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pwm_set_fan_duty_v0 *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_PWM_SET_FAN_DUTY, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_pwm_set_keyboard_backlight(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_pwm_set_keyboard_backlight *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_PWM_SET_KEYBOARD_BACKLIGHT, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_reboot_ec(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_reboot_ec *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_REBOOT_EC, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_regulator_enable(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_regulator_enable *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_REGULATOR_ENABLE, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_regulator_set_voltage(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_regulator_set_voltage *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_REGULATOR_SET_VOLTAGE, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_rwsig_action(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_rwsig_action *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_RWSIG_ACTION, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_set_base_state(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_set_base_state *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_SET_BASE_STATE, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_thermal_set_threshold(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_thermal_set_threshold *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_THERMAL_SET_THRESHOLD, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_thermal_set_threshold_v1(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_thermal_set_threshold_v1 *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_THERMAL_SET_THRESHOLD, 1,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_typec_control(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_typec_control *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_TYPEC_CONTROL, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_usb_charge_set_mode(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_charge_set_mode *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_CHARGE_SET_MODE, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_usb_mux(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_mux *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_MUX, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_usb_pd_dps_control(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_pd_dps_control *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_DPS_CONTROL, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_usb_pd_mux_ack(
	CROS_EC_COMMAND_INFO *h,
	const struct ec_params_usb_pd_mux_ack *p)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_MUX_ACK, 0,
			       p, sizeof(*p),
			       NULL, 0);
}

static inline int ec_cmd_flash_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_flash_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_FLASH_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_flash_spi_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_flash_spi_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_FLASH_SPI_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_fp_stats(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_fp_stats *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_FP_STATS, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_get_chip_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_get_chip_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_CHIP_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_get_features(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_get_features *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_FEATURES, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_get_next_event(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_get_next_event *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_NEXT_EVENT, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_get_protocol_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_get_protocol_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_PROTOCOL_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_get_version(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_get_version *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_VERSION, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_get_version_v1(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_get_version_v1 *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_GET_VERSION, 1,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_keyboard_factory_test(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_keyboard_factory_test *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_KEYBOARD_FACTORY_TEST, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_mkbp_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_mkbp_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_MKBP_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_pchg_count(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_pchg_count *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_PCHG_COUNT, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_port80_last_boot(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_port80_last_boot *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_PORT80_LAST_BOOT, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_power_info_v1(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_power_info_v1 *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_POWER_INFO, 1,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_pstore_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_pstore_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_PSTORE_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_pwm_get_keyboard_backlight(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_pwm_get_keyboard_backlight *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_PWM_GET_KEYBOARD_BACKLIGHT, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_rollback_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_rollback_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_ROLLBACK_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_rwsig_check_status(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_rwsig_check_status *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_RWSIG_CHECK_STATUS, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_rwsig_info(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_rwsig_info *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_RWSIG_INFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_sysinfo(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_sysinfo *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_SYSINFO, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_ports(
	CROS_EC_COMMAND_INFO *h,
	struct ec_response_usb_pd_ports *r)
{
	return CROS_EC_COMMAND(h, EC_CMD_USB_PD_PORTS, 0,
			       NULL, 0,
			       r, sizeof(*r));
}

static inline int ec_cmd_ap_reset(CROS_EC_COMMAND_INFO *h)
{
	return CROS_EC_COMMAND(h, EC_CMD_AP_RESET, 0,
			       NULL, 0,
			       NULL, 0);
}

static inline int ec_cmd_console_snapshot(CROS_EC_COMMAND_INFO *h)
{
	return CROS_EC_COMMAND(h, EC_CMD_CONSOLE_SNAPSHOT, 0,
			       NULL, 0,
			       NULL, 0);
}

static inline int ec_cmd_reboot(CROS_EC_COMMAND_INFO *h)
{
	return CROS_EC_COMMAND(h, EC_CMD_REBOOT, 0,
			       NULL, 0,
			       NULL, 0);
}

static inline int ec_cmd_thermal_auto_fan_ctrl(CROS_EC_COMMAND_INFO *h)
{
	return CROS_EC_COMMAND(h, EC_CMD_THERMAL_AUTO_FAN_CTRL, 0,
			       NULL, 0,
			       NULL, 0);
}

static inline int ec_cmd_tp_frame_snapshot(CROS_EC_COMMAND_INFO *h)
{
	return CROS_EC_COMMAND(h, EC_CMD_TP_FRAME_SNAPSHOT, 0,
			       NULL, 0,
			       NULL, 0);
}

static inline int ec_cmd_tp_self_test(CROS_EC_COMMAND_INFO *h)
{
	return CROS_EC_COMMAND(h, EC_CMD_TP_SELF_TEST, 0,
			       NULL, 0,
			       NULL, 0);
}

#ifdef __cplusplus
}
#endif

#endif /* __CROS_EC_EC_CMD_API_H */
