/* Copyright 2022 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/*
 * The rest of this file is generated by
 * util/host-command/api-gen.sh.
 */

/* clang-format off */

static inline int ec_cmd_adc_read(
	const struct ec_params_adc_read *p,
	struct ec_response_adc_read *r)
{
	return CROS_EC_COMMAND(EC_CMD_ADC_READ, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_battery_vendor_param(
	const struct ec_params_battery_vendor_param *p,
	struct ec_response_battery_vendor_param *r)
{
	return CROS_EC_COMMAND(EC_CMD_BATTERY_VENDOR_PARAM, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_cec_get(
	const struct ec_params_cec_get *p,
	struct ec_response_cec_get *r)
{
	return CROS_EC_COMMAND(EC_CMD_CEC_GET, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_chargesplash(
	const struct ec_params_chargesplash *p,
	struct ec_response_chargesplash *r)
{
	return CROS_EC_COMMAND(EC_CMD_CHARGESPLASH, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_device_event(
	const struct ec_params_device_event *p,
	struct ec_response_device_event *r)
{
	return CROS_EC_COMMAND(EC_CMD_DEVICE_EVENT, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_fp_mode(
	const struct ec_params_fp_mode *p,
	struct ec_response_fp_mode *r)
{
	return CROS_EC_COMMAND(EC_CMD_FP_MODE, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_get_cmd_versions(
	const struct ec_params_get_cmd_versions *p,
	struct ec_response_get_cmd_versions *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_CMD_VERSIONS, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_get_pd_port_caps(
	const struct ec_params_get_pd_port_caps *p,
	struct ec_response_get_pd_port_caps *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_PD_PORT_CAPS, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_hello(
	const struct ec_params_hello *p,
	struct ec_response_hello *r)
{
	return CROS_EC_COMMAND(EC_CMD_HELLO, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_hibernation_delay(
	const struct ec_params_hibernation_delay *p,
	struct ec_response_hibernation_delay *r)
{
	return CROS_EC_COMMAND(EC_CMD_HIBERNATION_DELAY, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_host_event(
	const struct ec_params_host_event *p,
	struct ec_response_host_event *r)
{
	return CROS_EC_COMMAND(EC_CMD_HOST_EVENT, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_i2c_control(
	const struct ec_params_i2c_control *p,
	struct ec_response_i2c_control *r)
{
	return CROS_EC_COMMAND(EC_CMD_I2C_CONTROL, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_locate_chip(
	const struct ec_params_locate_chip *p,
	struct ec_response_locate_chip *r)
{
	return CROS_EC_COMMAND(EC_CMD_LOCATE_CHIP, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_pd_chip_info(
	const struct ec_params_pd_chip_info *p,
	struct ec_response_pd_chip_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_PD_CHIP_INFO, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_pwm_get_duty(
	const struct ec_params_pwm_get_duty *p,
	struct ec_response_pwm_get_duty *r)
{
	return CROS_EC_COMMAND(EC_CMD_PWM_GET_DUTY, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_regulator_get_voltage(
	const struct ec_params_regulator_get_voltage *p,
	struct ec_response_regulator_get_voltage *r)
{
	return CROS_EC_COMMAND(EC_CMD_REGULATOR_GET_VOLTAGE, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_regulator_is_enabled(
	const struct ec_params_regulator_is_enabled *p,
	struct ec_response_regulator_is_enabled *r)
{
	return CROS_EC_COMMAND(EC_CMD_REGULATOR_IS_ENABLED, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_rgbkbd(
	const struct ec_params_rgbkbd *p,
	struct ec_response_rgbkbd *r)
{
	return CROS_EC_COMMAND(EC_CMD_RGBKBD, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_switch_enable_wireless_v1(
	const struct ec_params_switch_enable_wireless_v1 *p,
	struct ec_response_switch_enable_wireless_v1 *r)
{
	return CROS_EC_COMMAND(EC_CMD_SWITCH_ENABLE_WIRELESS, 1,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_temp_sensor_get_info(
	const struct ec_params_temp_sensor_get_info *p,
	struct ec_response_temp_sensor_get_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_TEMP_SENSOR_GET_INFO, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_thermal_get_threshold(
	const struct ec_params_thermal_get_threshold *p,
	struct ec_response_thermal_get_threshold *r)
{
	return CROS_EC_COMMAND(EC_CMD_THERMAL_GET_THRESHOLD, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_tmp006_get_raw(
	const struct ec_params_tmp006_get_raw *p,
	struct ec_response_tmp006_get_raw *r)
{
	return CROS_EC_COMMAND(EC_CMD_TMP006_GET_RAW, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_control(
	const struct ec_params_usb_pd_control *p,
	struct ec_response_usb_pd_control *r)
{
	return CROS_EC_COMMAND(EC_CMD_USB_PD_CONTROL, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_mux_info(
	const struct ec_params_usb_pd_mux_info *p,
	struct ec_response_usb_pd_mux_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_USB_PD_MUX_INFO, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_power_info(
	const struct ec_params_usb_pd_power_info *p,
	struct ec_response_usb_pd_power_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_USB_PD_POWER_INFO, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_vboot_hash(
	const struct ec_params_vboot_hash *p,
	struct ec_response_vboot_hash *r)
{
	return CROS_EC_COMMAND(EC_CMD_VBOOT_HASH, 0,
		   p, sizeof(*p),
		   r, sizeof(*r));
}

static inline int ec_cmd_button(
	const struct ec_params_button *p)
{
	return CROS_EC_COMMAND(EC_CMD_BUTTON, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_cec_set(
	const struct ec_params_cec_set *p)
{
	return CROS_EC_COMMAND(EC_CMD_CEC_SET, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_config_power_button(
	const struct ec_params_config_power_button *p)
{
	return CROS_EC_COMMAND(EC_CMD_CONFIG_POWER_BUTTON, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_efs_verify(
	const struct ec_params_efs_verify *p)
{
	return CROS_EC_COMMAND(EC_CMD_EFS_VERIFY, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_external_power_limit_v1(
	const struct ec_params_external_power_limit_v1 *p)
{
	return CROS_EC_COMMAND(EC_CMD_EXTERNAL_POWER_LIMIT, 1,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_flash_erase(
	const struct ec_params_flash_erase *p)
{
	return CROS_EC_COMMAND(EC_CMD_FLASH_ERASE, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_force_lid_open(
	const struct ec_params_force_lid_open *p)
{
	return CROS_EC_COMMAND(EC_CMD_FORCE_LID_OPEN, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_fp_seed(
	const struct ec_params_fp_seed *p)
{
	return CROS_EC_COMMAND(EC_CMD_FP_SEED, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_gpio_set(
	const struct ec_params_gpio_set *p)
{
	return CROS_EC_COMMAND(EC_CMD_GPIO_SET, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_hang_detect(
	const struct ec_params_hang_detect *p)
{
	return CROS_EC_COMMAND(EC_CMD_HANG_DETECT, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_mkbp_simulate_key(
	const struct ec_params_mkbp_simulate_key *p)
{
	return CROS_EC_COMMAND(EC_CMD_MKBP_SIMULATE_KEY, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_pd_control(
	const struct ec_params_pd_control *p)
{
	return CROS_EC_COMMAND(EC_CMD_PD_CONTROL, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_pd_write_log_entry(
	const struct ec_params_pd_write_log_entry *p)
{
	return CROS_EC_COMMAND(EC_CMD_PD_WRITE_LOG_ENTRY, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_pstore_write(
	const struct ec_params_pstore_write *p)
{
	return CROS_EC_COMMAND(EC_CMD_PSTORE_WRITE, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_pwm_set_duty(
	const struct ec_params_pwm_set_duty *p)
{
	return CROS_EC_COMMAND(EC_CMD_PWM_SET_DUTY, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_pwm_set_keyboard_backlight(
	const struct ec_params_pwm_set_keyboard_backlight *p)
{
	return CROS_EC_COMMAND(EC_CMD_PWM_SET_KEYBOARD_BACKLIGHT, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_reboot_ec(
	const struct ec_params_reboot_ec *p)
{
	return CROS_EC_COMMAND(EC_CMD_REBOOT_EC, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_regulator_enable(
	const struct ec_params_regulator_enable *p)
{
	return CROS_EC_COMMAND(EC_CMD_REGULATOR_ENABLE, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_regulator_set_voltage(
	const struct ec_params_regulator_set_voltage *p)
{
	return CROS_EC_COMMAND(EC_CMD_REGULATOR_SET_VOLTAGE, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_rwsig_action(
	const struct ec_params_rwsig_action *p)
{
	return CROS_EC_COMMAND(EC_CMD_RWSIG_ACTION, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_set_base_state(
	const struct ec_params_set_base_state *p)
{
	return CROS_EC_COMMAND(EC_CMD_SET_BASE_STATE, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_thermal_set_threshold(
	const struct ec_params_thermal_set_threshold *p)
{
	return CROS_EC_COMMAND(EC_CMD_THERMAL_SET_THRESHOLD, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_typec_control(
	const struct ec_params_typec_control *p)
{
	return CROS_EC_COMMAND(EC_CMD_TYPEC_CONTROL, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_usb_charge_set_mode(
	const struct ec_params_usb_charge_set_mode *p)
{
	return CROS_EC_COMMAND(EC_CMD_USB_CHARGE_SET_MODE, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_usb_mux(
	const struct ec_params_usb_mux *p)
{
	return CROS_EC_COMMAND(EC_CMD_USB_MUX, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_usb_pd_dps_control(
	const struct ec_params_usb_pd_dps_control *p)
{
	return CROS_EC_COMMAND(EC_CMD_USB_PD_DPS_CONTROL, 0,
		   p, sizeof(*p),
		   NULL, 0);
}

static inline int ec_cmd_flash_info(
	struct ec_response_flash_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_FLASH_INFO, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_flash_spi_info(
	struct ec_response_flash_spi_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_FLASH_SPI_INFO, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_fp_stats(
	struct ec_response_fp_stats *r)
{
	return CROS_EC_COMMAND(EC_CMD_FP_STATS, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_get_chip_info(
	struct ec_response_get_chip_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_CHIP_INFO, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_get_features(
	struct ec_response_get_features *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_FEATURES, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_get_protocol_info(
	struct ec_response_get_protocol_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_PROTOCOL_INFO, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_get_version(
	struct ec_response_get_version *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_VERSION, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_get_version_v1(
	struct ec_response_get_version_v1 *r)
{
	return CROS_EC_COMMAND(EC_CMD_GET_VERSION, 1,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_keyboard_factory_test(
	struct ec_response_keyboard_factory_test *r)
{
	return CROS_EC_COMMAND(EC_CMD_KEYBOARD_FACTORY_TEST, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_pchg_count(
	struct ec_response_pchg_count *r)
{
	return CROS_EC_COMMAND(EC_CMD_PCHG_COUNT, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_port80_last_boot(
	struct ec_response_port80_last_boot *r)
{
	return CROS_EC_COMMAND(EC_CMD_PORT80_LAST_BOOT, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_pstore_info(
	struct ec_response_pstore_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_PSTORE_INFO, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_pwm_get_keyboard_backlight(
	struct ec_response_pwm_get_keyboard_backlight *r)
{
	return CROS_EC_COMMAND(EC_CMD_PWM_GET_KEYBOARD_BACKLIGHT, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_rollback_info(
	struct ec_response_rollback_info *r)
{
	return CROS_EC_COMMAND(EC_CMD_ROLLBACK_INFO, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_rwsig_check_status(
	struct ec_response_rwsig_check_status *r)
{
	return CROS_EC_COMMAND(EC_CMD_RWSIG_CHECK_STATUS, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_usb_pd_ports(
	struct ec_response_usb_pd_ports *r)
{
	return CROS_EC_COMMAND(EC_CMD_USB_PD_PORTS, 0,
		   NULL, 0,
		   r, sizeof(*r));
}

static inline int ec_cmd_ap_reset(void)
{
	return CROS_EC_COMMAND(EC_CMD_AP_RESET, 0,
		   NULL, 0,
		   NULL, 0);
}

static inline int ec_cmd_console_snapshot(void)
{
	return CROS_EC_COMMAND(EC_CMD_CONSOLE_SNAPSHOT, 0,
		   NULL, 0,
		   NULL, 0);
}

static inline int ec_cmd_reboot(void)
{
	return CROS_EC_COMMAND(EC_CMD_REBOOT, 0,
		   NULL, 0,
		   NULL, 0);
}

static inline int ec_cmd_thermal_auto_fan_ctrl(void)
{
	return CROS_EC_COMMAND(EC_CMD_THERMAL_AUTO_FAN_CTRL, 0,
		   NULL, 0,
		   NULL, 0);
}

static inline int ec_cmd_tp_frame_snapshot(void)
{
	return CROS_EC_COMMAND(EC_CMD_TP_FRAME_SNAPSHOT, 0,
		   NULL, 0,
		   NULL, 0);
}

static inline int ec_cmd_tp_self_test(void)
{
	return CROS_EC_COMMAND(EC_CMD_TP_SELF_TEST, 0,
		   NULL, 0,
		   NULL, 0);
}
