// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef __CROS_EC_STATE_CACHE_STATE_CACHE_TAGS_H_
#define __CROS_EC_STATE_CACHE_STATE_CACHE_TAGS_H_

enum state_cache_uint8_tag {
    STATE_CACHE_UINT8_TAG_CURRENT_TASK = 0,
    STATE_CACHE_UINT8_TAG_LAST_HOOK,
    STATE_CACHE_UINT8_TAG_LAST_IRQ,
    STATE_CACHE_UINT8_TAG_IN_ISR,
    STATE_CACHE_UINT8_TAG_IMAGE,
    STATE_CACHE_UINT8_TAG_BATTERY_LEVEL,
    STATE_CACHE_UINT8_TAG_BATTERY_STATUS,
    STATE_CACHE_UINT8_TAG_CHARGE_STATE,
    STATE_CACHE_UINT8_TAG_PHYSICAL_STATE,
    STATE_CACHE_UINT8_TAG_PD0_STATE,
    STATE_CACHE_UINT8_TAG_PD1_STATE,

    STATE_CACHE_UINT8_TAG_COUNT
};

enum state_cache_uint16_tag {
    STATE_CACHE_UINT16_TAG_LAST_IRQ_COUNT = 0,
    STATE_CACHE_UINT16_TAG_LAST_HOST_COMMAND,
    STATE_CACHE_UINT16_TAG_POWER_STATE,
    STATE_CACHE_UINT16_TAG_POWER_SIGNALS,

    STATE_CACHE_UINT16_TAG_COUNT
};

enum state_cache_uint32_tag {
    STATE_CACHE_UINT32_TAG_ELAPSED_TIME_MS = 0,
    STATE_CACHE_UINT32_TAG_LAST_IRQ_COUNT,
    STATE_CACHE_UINT32_TAG_LAST_PORT80,
    STATE_CACHE_UINT32_TAG_RESET_FLAGS,

    STATE_CACHE_UINT32_TAG_COUNT
};

enum state_cache_uint64_tag {
    STATE_CACHE_UINT64_TAG_HOST_EVENT = 0,

    STATE_CACHE_UINT64_TAG_COUNT
};

#endif  // __CROS_EC_STATE_CACHE_STATE_CACHE_TAGS_H_
