/* Copyright 2024 The ChromiumOS Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef MTLRVP_MCHP_BOARD_H_
#define MTLRVP_MCHP_BOARD_H_

#include <dt-bindings/gpio/microchip-xec-gpio.h>

/* Power Signals */
#define PWR_EN_PP3300_S5 MCHP_GPIO_DECODE_025
#define PWR_RSMRST_PWRGD MCHP_GPIO_DECODE_011
#define PWR_EC_PCH_RSMRST MCHP_GPIO_DECODE_054
#define PWR_SLP_S0 MCHP_GPIO_DECODE_002
#define PWR_PCH_PWROK MCHP_GPIO_DECODE_106
#define PWR_EC_PCH_SYS_PWROK MCHP_GPIO_DECODE_202
#define PWR_SYS_RST MCHP_GPIO_DECODE_165
#define PWR_ALL_SYS_PWRGD MCHP_GPIO_DECODE_057

/* USB-C signals */
#define GPIO_CCD_MODE_ODL MCHP_GPIO_DECODE_242
#define GPIO_USBC_TCPC_ALRT_P0 MCHP_GPIO_DECODE_143
#define GPIO_USB_C0_C1_TCPC_RST_ODL MCHP_GPIO_DECODE_240
#define GPIO_USBC_TCPC_PPC_ALRT_P0 MCHP_GPIO_DECODE_241
#define GPIO_USBC_TCPC_PPC_ALRT_P1 MCHP_GPIO_DECODE_155
#define GPIO_USBC_TCPC_ALRT_P2 MCHP_GPIO_DECODE_221
#define GPIO_USBC_TCPC_ALRT_P3 MCHP_GPIO_DECODE_034

#define I2C_TYPEC_AIC1 i2c_smb_1
#define I2C_TYPEC_AIC2 i2c_smb_2

#endif /* MTLRVP_MCHP_BOARD_H_ */