# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Core EC configuration: build the EC application, using ECOS shims
# (which are currently required for a number of features).
CONFIG_CROS_EC=y
CONFIG_PLATFORM_EC=y
CONFIG_SHIMMED_TASKS=y
CONFIG_LTO=y

# Debug options and features; can be disabled to save memory
CONFIG_SHELL_MINIMAL=n
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
#
# TODO(b/216921645): Remove when fixed
#
CONFIG_SOC_POWER_MANAGEMENT_TRACE=n

# Standard shimmed features
CONFIG_PLATFORM_EC_BACKLIGHT_LID=y
CONFIG_PLATFORM_EC_CONSOLE_CMD_SYSINFO=y
CONFIG_PLATFORM_EC_I2C=y
CONFIG_PLATFORM_EC_LID_SWITCH=y
CONFIG_PLATFORM_EC_POWER_BUTTON=y
CONFIG_PLATFORM_EC_SWITCH=y
CONFIG_PLATFORM_EC_VBOOT_EFS2=y
CONFIG_PLATFORM_EC_VBOOT_HASH=y

# Application processor; communicates with EC via eSPI
CONFIG_AP=y
CONFIG_AP_X86_INTEL_ADL=y
CONFIG_ESPI=y
CONFIG_PLATFORM_EC_ESPI_VW_SLP_S4=y
CONFIG_PLATFORM_EC_HOSTCMD=y