# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# matsu board-specific Kconfig settings.

CONFIG_BOARD_MATSU=y

CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y

# Disable options not yet configured

# PDC
CONFIG_PDC_RUNTIME_PORT_CONFIG=n
CONFIG_USBC_PDC_TPS6699X_CONSOLE_FW_UPDATER=n
