# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# matsu board-specific Kconfig settings.

CONFIG_BOARD_MATSU=y

CONFIG_PLATFORM_EC_KEYBOARD_CUSTOMIZATION=y

# AP to EC communication
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S3=n
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S4=n
CONFIG_PLATFORM_EC_HOST_INTERFACE_ESPI_VW_SLP_S5=y
CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y
CONFIG_PLATFORM_EC_CMD_BUTTON=y
CONFIG_HCDEBUG_OFF=y

# Lid
CONFIG_PLATFORM_EC_BACKLIGHT_LID=y

# EFS2
CONFIG_PLATFORM_EC_VBOOT_EFS2=y

# Disable options not yet configured

# PDC
CONFIG_PDC_RUNTIME_PORT_CONFIG=n
CONFIG_USBC_PDC_TPS6699X_CONSOLE_FW_UPDATER=n
