# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_PTLERB_MCHP=y
CONFIG_CROS_FLASH_XEC=y
CONFIG_CROS_SYSTEM_XEC=y
CONFIG_CROS_KB_RAW_XEC=n
CONFIG_SYSCON=n

# Power Sequencing
CONFIG_AP_X86_INTEL_MTL=y
CONFIG_X86_NON_DSX_PWRSEQ_MTL=y

# For MCHP ESPI Drivers
CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD=y
CONFIG_ESPI_PERIPHERAL_ACPI_SHM_REGION=y
CONFIG_ESPI_PERIPHERAL_CUSTOM_OPCODE=y
CONFIG_ESPI_PERIPHERAL_XEC_EMI0=y
CONFIG_ESPI_PERIPHERAL_ACPI_EC_IBF_EVT_DATA=y
CONFIG_ESPI_PERIPHERAL_KBC_OBE_CBK=y
CONFIG_ESPI_PERIPHERAL_KBC_IBF_EVT_DATA=y

# Power Delivery
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_CHARGER=y

# Invoke SoC Python script to create zephyr.mchp.bin which
# is zephyr.bin processed for Boot-ROM loading.
CONFIG_MCHP_MEC_UNSIGNED_HEADER=y
CONFIG_MCHP_MEC_HEADER_FLASH_SIZE_256K=y

# Support Zephyr SPI NOR driver to work with MCHP SPI driver
CONFIG_SPI_NOR=y
#CONFIG_SPI_XEC_QMSPI_FULL_DUPLEX=y

# Fan / TACH support
CONFIG_PWM_XEC=y
CONFIG_TACH_XEC=y

# TODO: Enable RTC
CONFIG_PLATFORM_EC_RTC=n

# Enable power delivery debug log
CONFIG_USB_PDC_LOG_LEVEL_DBG=y

# I2C driver init pri
CONFIG_I2C_INIT_PRIORITY=29

CONFIG_PLATFORM_EC_HOSTCMD_AP_RESET=n
CONFIG_PLATFORM_EC_CHARGER_RAA489110=y
CONFIG_PLATFORM_EC_POWER_BUTTON_IGNORE_LID=y

CONFIG_PLATFORM_EC_TABLET_MODE=y
CONFIG_PLATFORM_EC_GMR_TABLET_MODE=y
