# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_TRULO_CHRE_EXPERIMENT=y
CONFIG_CHRE_PIGWEED_PLATFORM=y

# Can't select a Kconfig choice, so enable it
CONFIG_PIGWEED_LOG_ZEPHYR=y
