# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_TRULO_CHRE_EXPERIMENT=y
CONFIG_PIGWEED_CHRONO_SYSTEM_TIMER=y
CONFIG_PIGWEED_LOG_ZEPHYR=y
CONFIG_PIGWEED_SYNC_THREAD_NOTIFICATION=y
CONFIG_PIGWEED_SYNC_TIMED_THREAD_NOTIFICATION=y
CONFIG_PIGWEED_SYS_IO=y
CONFIG_PIGWEED_THREAD=y
