# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ET171=y
# Flash is mapped at 0x80000000
CONFIG_PLATFORM_EC_MAPPED_STORAGE_BASE=0x80000000

CONFIG_CROS_FLASH=y
CONFIG_PLATFORM_EC_NOINIT_END_OF_RAM_SECTION=n
# 1MB flash
CONFIG_PLATFORM_EC_FLASH_SIZE_BYTES=1048576
CONFIG_XIP=y

CONFIG_EXCEPTION_DEBUG=y
CONFIG_PLATFORM_EC_ROLLBACK_MPU_PROTECT=n

# TODO: FIX: TX interupt drivern uart doesn't work - shell doesn't respond to input (only first enter)
CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y

# WDT
# Max posibble value. TODO verify
CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=500
# Disable till timer -> hook_tick is fixed 
CONFIG_WDT_DISABLE_AT_BOOT=y
# Set HOOK_TICK INTERVAL in microseconds to reload watchdog
CONFIG_CROS_EC_HOOK_TICK_INTERVAL=200000
CONFIG_PLATFORM_EC_WATCHDOG_WARNING_LEADING_TIME_MS=50
#CONFIG_PLATFORM_EC_WATCHDOG_HELPER=y

# Make space for SDCP info
CONFIG_SRAM_SIZE=383

# Enable USB for HC
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# TODO determine a proper value
CONFIG_UDC_BUF_POOL_SIZE=2048

# Disable for bring-up

# BoringSSL support
#CONFIG_BORINGSSL_CRYPTO=n
#CONFIG_BORINGSSL_HARDWARE_ENTROPY=n

# Power Management
CONFIG_PM=n
CONFIG_PM_DEVICE=n

CONFIG_LOG_PRINTK=n

CONFIG_USB_DEVICE_MANUFACTURER="dawidn"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0xFACE
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="abcde"

# TODO determine a proper value
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=512
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=512

CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_CUSTOM=y

CONFIG_FPU=y
CONFIG_FPU_SHARING=n
# set to =n for compiler-rt
CONFIG_FLOAT_HARD=n
CONFIG_SINGLE_PRECISION_FPU=y
