# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ET171=y
# Flash is mapped at 0x80000000
# TODO rework to get from dts
CONFIG_PLATFORM_EC_MAPPED_STORAGE_BASE=0x80000000
CONFIG_FLASH_BASE_ADDRESS=0x80000000

CONFIG_PLATFORM_EC_NOINIT_END_OF_RAM_SECTION=n
# Hardcode 1MB flash in hex for now
CONFIG_PLATFORM_EC_FLASH_SIZE_BYTES=100000
CONFIG_XIP=y

CONFIG_EXCEPTION_DEBUG=y
CONFIG_PLATFORM_EC_ROLLBACK_MPU_PROTECT=n

# TODO: FIX: TX interupt drivern uart doesn't work - shell doesn't respond to input (only first enter)
#CONFIG_SHELL_BACKEND_SERIAL_API_POLLING=y

# WDT
# RWSIG takes more than 500ms, which causes not reloading WDT
CONFIG_WDT_DISABLE_AT_BOOT=y
# Max posibble value
CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=500
# Disable till timer -> hook_tick is fixed 
# Set HOOK_TICK INTERVAL in microseconds to reload watchdog
# Lower the tick interval to have wdt period > 2 * reload period
#CONFIG_CROS_EC_HOOK_TICK_INTERVAL=200000
# Andes watchdog doesn't support warnings before the actual reset
CONFIG_PLATFORM_EC_WATCHDOG_WARNING_LEADING_TIME_MS=0

# Enable USB for HC
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# TODO determine a proper value
CONFIG_UDC_BUF_POOL_SIZE=2048
CONFIG_USB_DEVICE_MAX_POWER=250

CONFIG_USB_DEVICE_MANUFACTURER="Google"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0xFACE
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="0"

# Use USB for signaling MKBP events
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_CUSTOM=y

# TODO determine a proper value
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=528
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=520

CONFIG_FPU_SHARING=n
CONFIG_FLOAT_HARD=y

# SPI/Flash related configs
CONFIG_SPI_NOR=n
CONFIG_FLASH_ANDES_QSPI_XIP_COUNT_REGS=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000

# No access to hardware WP pin, use custome method
CONFIG_PLATFORM_EC_WP_CUSTOM=y

# Page layout is needed for Flash Shell, but Flash XIP driver doesn't read it in runtime
CONFIG_FLASH_SHELL=n

# Disable for bring-up

# Power Management
CONFIG_PM=n
CONFIG_PM_DEVICE=n

CONFIG_LOG_PRINTK=n

# BBRAM not supported
CONFIG_BBRAM=n
# Page layout is needed for Flash Shell, but Flash XIP driver doesn't read it in runtime
CONFIG_FLASH_SHELL=n

CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000

# Make possibility to enter bootloader to reflash
CONFIG_PLATFORM_EC_HOST_COMMAND_ENTER_BOOTLOADER=y
