# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_ET171=y

CONFIG_PLATFORM_EC_NOINIT_END_OF_RAM_SECTION=n
# Hardcode 1MB flash in hex for now
CONFIG_PLATFORM_EC_FLASH_SIZE_BYTES=100000
CONFIG_XIP=y

CONFIG_EXCEPTION_DEBUG=y
CONFIG_PLATFORM_EC_ROLLBACK_MPU_PROTECT=y

# WDT
# RWSIG takes more than 500ms, which causes not reloading WDT
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_PLATFORM_EC_HOOK_TICK=n
# Max posibble value
#CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=500
# Disable till timer -> hook_tick is fixed
# Set HOOK_TICK INTERVAL in microseconds to reload watchdog
# Lower the tick interval to have wdt period > 2 * reload period
#CONFIG_CROS_EC_HOOK_TICK_INTERVAL=200000
# Andes watchdog doesn't support warnings before the actual reset
#CONFIG_PLATFORM_EC_WATCHDOG_WARNING_LEADING_TIME_MS=0

# Enable USB for HC
CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# TODO determine a proper value
CONFIG_UDC_BUF_POOL_SIZE=2048
CONFIG_USB_DEVICE_MAX_POWER=250

CONFIG_USB_DEVICE_MANUFACTURER="Google"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="0"
CONFIG_USB_DEVICE_SN_HWINFO=y

# Use USB for signaling MKBP events
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_USB=y

# TODO determine a proper value
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=528
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=520

CONFIG_FPU_SHARING=n
CONFIG_FLOAT_HARD=y

# SPI/Flash related configs
CONFIG_SPI_NOR=n
CONFIG_FLASH_ANDES_QSPI_XIP_COUNT_REGS=y
CONFIG_HEAP_MEM_POOL_SIZE=1024

# Use standar 0.1ms tick
CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000

# No access to hardware WP pin, use custome method
CONFIG_PLATFORM_EC_WP_CUSTOM=y

# FPS related configs
CONFIG_FINGERPRINT_SENSOR_EGIS630_HEAP_SIZE=112640

# Enable the fp vendor command to get MT data
CONFIG_PLATFORM_EC_FINGERPRINT_VENDOR_COMMAND=y

# BBRAM not supported on ET171
CONFIG_BBRAM=n

# Make possibility to enter bootloader
CONFIG_PLATFORM_EC_HOST_COMMAND_ENTER_BOOTLOADER=y

# Disable kernel shell, becasue it requires addtional 5kB of flash
CONFIG_KERNEL_SHELL=n

# The flash shell requires page layout which is not supported
CONFIG_FLASH_SHELL=n

# The default value is assigned base on an offset within ec-ro node, not wp-ro,
# which is not the same in this case.
CONFIG_PLATFORM_EC_RO_PUBKEY_STORAGE_OFF=261056
CONFIG_CROS_EC_RO_MEM_OFF=0x1000
CONFIG_CROS_EC_RO_SIZE=0x3f000

# RO size - 64 bytes of signature. Doesn't matter for RW
CONFIG_SOC_EGIS_ET171_VENDOR_FIRMWARE_SIZE=0x3efc0

# Leave printk till firmware is fully developed.
CONFIG_LOG_PRINTK=n

#RISCV PMP entry configurations
# b/406946889: Allow modifying PMP entries so that we can reconfigure them
# when jumping between RO and RW.
CONFIG_PMP_NO_LOCK_GLOBAL=y
CONFIG_NULL_POINTER_EXCEPTION_DETECTION_PMP=y
CONFIG_HW_STACK_PROTECTION=y
CONFIG_MEM_ATTR=y

# Use EGIS ET171's secure OTP storage for keys.
CONFIG_EGIS_ET171_OTP_KEY=y
