# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Module for testing TPM2 commands."""
import time
import subcmd
import utils
import struct

TPM_SU_CLEAR = 0x0000
TPM_SU_STATE = 0x0001

def tpm2_startup(tpm, state):
    """Send TPM2_Startup command

    Args:
        tpm: a tpm object used to communicate with the device
        state: TPM_SU_CLEAR / TPM_SU_STATE

    Raises:
        subcmd.TpmTestError: on unexpected target responses
    """
    startup = [0x80, 0x01,      # TPM_ST_NO_SESSIONS
            0x00, 0x00, 0x00, 0x0c, # commandSize = 12
            0x00, 0x00, 0x01, 0x44, # TPM_CC_Startup
            0x00, 0x00,            # TPM_SU_CLEAR / TPM_SU_STATE
      ]
    startup[10:12] = state.to_bytes(2, byteorder='big')
    cmd = bytes(startup)
    response = tpm.command(cmd)
    return response

def tpm2_shutdown(tpm, state):
    """Send TPM2_Shutdown command

    Args:
        tpm: a tpm object used to communicate with the device
        state: TPM_SU_CLEAR / TPM_SU_STATE

    Raises:
        subcmd.TpmTestError: on unexpected target responses
    """
    shutdown = [        0x80, 0x01, # tag: TPM_ST_NO_SESSIONS
        0x00, 0x00, 0x00, 0x0c, # size:
        0x00, 0x00, 0x01, 0x45, # command: TPM_CC_Shutdown
        # ======
        0x00, 0x00, # shutdown type: TPM_SU_STATE
      ]
    shutdown[10:12] = state.to_bytes(2, byteorder='big')
    cmd = bytes(shutdown)
    response = tpm.command(cmd)
    return response

# TEST_SIGN:
# OP | CURVE_ID | SIGN_MODE | HASHING | DIGEST_LEN | DIGEST
#    @returns 0/1 | R_LEN | R | S_LEN | S
# def sb_cmd(curve_id, hash_func, sign_mode, msg):
#     digest = hash_func(msg).digest()
#     return struct.pack('>BBBBH', _ECC_OPCODES['SIGN'], curve_id, sign_mode,
#                       _HASH['NONE'], len(digest)) + digest

def wrap_sb_command(subcmd_code, cmd_body):
    """Wrap TPM command into extension command header"""
    return struct.pack('>H2IH', 0x8001,
                        len(cmd_body) + struct.calcsize('>H2IH'),
                        0x20000001, subcmd_code) + cmd_body

def unwrap_ext_response(self, expected_subcmd, response):
    """Verify basic validity and strip off TPM extended command header.

    Get the response generated by the device, as it came off the wire,
    verify that header fields match expectations, then strip off the
    extension command header and return the payload to the caller.

    Args:
        expected_subcmd: an int, up to 16 bits in size, the extension
            command this response is supposed to be for.
        response: a binary string, the actual response received
            over the wire.

    Returns:
        the binary string of the response payload,
        if validation succeeded.

    Raises:
        subcmd.TpmTestError: in case there are any validation problems,
        the error message describes the problem.
    """
    header_size = struct.calcsize('>H2IH')
    tag, size, cmd, sub = struct.unpack('>H2IH',
                                        response[:header_size])
    if tag != 0x8001:
        raise subcmd.TpmTestError('Wrong response tag: %4.4x' % tag)
    if cmd:
        raise subcmd.TpmTestError('Unexpected response command'
                                    ' field: %8.8x' % cmd)
    if sub != expected_subcmd:
        raise subcmd.TpmTestError('Unexpected response subcommand'
                                    ' field: %2.2x' % sub)
    if size != len(response):
        raise subcmd.TpmTestError('Size mismatch: header %d, actual %d' %
                                    (size, len(response)))
    return response[header_size:]

def sb_test(tpm):
    """Run TPM2 startup/shutdown in a loop tests"""
    tpm2_startup(tpm, TPM_SU_CLEAR)
    w_rsp = tpm.command(wrap_sb_command(0x11, b""))
    rsp = unwrap_ext_response(0x11, w_rsp)
    print(rsp)
    tpm2_shutdown(tpm, TPM_SU_STATE)
