# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Template size for FT9869 sensor
CONFIG_FP_ALGORITHM_TEMPLATE_SIZE=24576
CONFIG_USB_DEVICE_PID=0x5404
