# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_FT9001=y

# The NULL pointer exception page size must be a power of two
# and have size greater or equal ARM_MPU_REGION_MIN_ALIGN_AND_SIZE
CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE=0x80

# Peripherials
CONFIG_GPIO=y


#Bringup configs

# Power Management
CONFIG_PM=n
CONFIG_PM_DEVICE=n

# Logging
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_LOG_PRINTK=n

# Shell commands
CONFIG_FLASH_SHELL=n

# MKBP
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_CUSTOM=y

CONFIG_EC_HOST_CMD=n
# Enable USB for HC
#CONFIG_UDC_DRIVER=y
#CONFIG_USB_DEVICE_STACK_NEXT=y
# TODO determine a proper value
#CONFIG_UDC_BUF_POOL_SIZE=2048

CONFIG_PLATFORM_EC_PANIC_STRIP_GPR=n

# First 0x1000 bytes of the flash is for boot data
CONFIG_CROS_EC_RO_MEM_OFF=0x1000
CONFIG_CROS_EC_RW_MEM_OFF=0x80000

CONFIG_INIT_ARCH_HW_AT_BOOT=y
CONFIG_EXCEPTION_DEBUG=y
CONFIG_EXTRA_EXCEPTION_INFO=y

CONFIG_USB_DEVICE_MANUFACTURER="dawidn"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0xFACE
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="abcde"
CONFIG_USB_DEVICE_MAX_POWER=250

CONFIG_TASK_FPSENSOR_STACK_SIZE=16184

# To reduce RAM useage
CONFIG_MAIN_STACK_SIZE=3072
