# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_USB_PD_ALTMODE=y
CONFIG_USB_PD_ALTMODE_INTEL=y
CONFIG_BOARD_MTLRVP_PD=y
CONFIG_PDC_CCG8_PWR_MGNT=n
CONFIG_PLATFORM_EC_USB_PD_VBUS_MEASURE_BY_BOARD=y
CONFIG_SMF=y
CONFIG_SMF_ANCESTOR_SUPPORT=y
