#ifndef PTLERB_MCHP_POWER_SIGNALS_H_
#define PTLERB_MCHP_POWER_SIGNALS_H_

#define PWR_EN_PP3300_S5     MCHP_GPIO_DECODE_226 GPIO_ACTIVE_HIGH
#define PWR_RSMRST_PWRGD     MCHP_GPIO_DECODE_012 GPIO_ACTIVE_HIGH
#define PWR_EC_PCH_RSMRST    MCHP_GPIO_DECODE_054 GPIO_ACTIVE_LOW
#define PWR_SLP_S0           MCHP_GPIO_DECODE_052 GPIO_ACTIVE_LOW
#define PWR_PCH_PWROK        MCHP_GPIO_DECODE_100 GPIO_OPEN_DRAIN
#define PWR_EC_PCH_SYS_PWROK MCHP_GPIO_DECODE_015 GPIO_OPEN_DRAIN
#define PWR_ALL_SYS_PWRGD    MCHP_GPIO_DECODE_057 GPIO_ACTIVE_HIGH

#endif /* PTLERB_MCHP_POWER_SIGNALS_H_ */
