# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_EM32F967=y

# The NULL pointer exception page size must be a power of two
# and have size greater or equal ARM_MPU_REGION_MIN_ALIGN_AND_SIZE
CONFIG_CORTEX_M_NULL_POINTER_EXCEPTION_PAGE_SIZE=0x80

# Peripherials
CONFIG_GPIO=y


#Bringup configs

# Power Management
CONFIG_PM=n
CONFIG_PM_DEVICE=n

# Logging
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_LOG_PRINTK=n

# Shell commands
CONFIG_FLASH_SHELL=n

# MKBP
CONFIG_PLATFORM_EC_MKBP_USE_GPIO=n
CONFIG_PLATFORM_EC_MKBP_USE_CUSTOM=y

CONFIG_EC_HOST_CMD=y

CONFIG_ARM_MPU=y
CONFIG_MPU=y

CONFIG_UDC_DRIVER=y
CONFIG_USB_DEVICE_STACK_NEXT=y
# TODO determine a proper value
CONFIG_UDC_BUF_POOL_SIZE=2048

CONFIG_PLATFORM_EC_PANIC_STRIP_GPR=n

CONFIG_INIT_ARCH_HW_AT_BOOT=y
CONFIG_EXCEPTION_DEBUG=y
CONFIG_EXTRA_EXCEPTION_INFO=y

CONFIG_USB_DEVICE_MANUFACTURER="dawidn"
CONFIG_USB_DEVICE_PRODUCT="FPMCU"
CONFIG_USB_DEVICE_VID=0x18D1
CONFIG_USB_DEVICE_PID=0xFACE
CONFIG_USB_DEVICE_SELF_POWERED=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y
CONFIG_USB_DEVICE_SN="abcde"
CONFIG_USB_DEVICE_MAX_POWER=250

#CONFIG_SYS_CLOCK_TICKS_PER_SEC=100
CONFIG_HW_STACK_PROTECTION=y

CONFIG_FP_MAX_FINGER_COUNT=2

# TODO determine a proper value
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=528
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=520
