# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#CONFIG_HELIPILOT_EC_RO_QUIRKS=y
#CONFIG_CROS_FLASH_STM32_EC_JUMP_STRUCTURE=y
