# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_HELIPILOT=y

# Hwinfo (used by cros-system driver)
CONFIG_HWINFO=y

# NPCX Flash driver options
CONFIG_PLATFORM_EC_USE_ZEPHYR_FLASH_PAGE_LAYOUT=y

# NPCX entropy driver options
CONFIG_ENTROPY_GENERATOR=y
#CONFIG_NPCX_DRBG=y
#CONFIG_ENTROPY_NPCX_DRBG=y

# set security strength to 256b
# CONFIG_ENTROPY_NPCX_DRBG_SECURITY_STRENGTH=3

# Watchdog
CONFIG_WATCHDOG=y
#CONFIG_WDT_NPCX=y
#CONFIG_IWDG_STM32_INITIAL_TIMEOUT=10000
#CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=10000
#CONFIG_PLATFORM_EC_WATCHDOG_WARNING_LEADING_TIME_MS=3000

# CrOS drivers
#CONFIG_CROS..

# Priorities
CONFIG_PLATFORM_EC_FLASH_INIT_PRIORITY=60
#CONFIG_CROS_SYSTEM_NPCX_INIT_PRIORITY=71
CONFIG_PLATFORM_EC_SYSTEM_PRE_INIT_PRIORITY=72

# Host Commands
CONFIG_EC_HOST_CMD_INITIALIZE_AT_BOOT=n
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=549
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=544
CONFIG_EC_HOST_CMD_BACKEND_SPI=y
#CONFIG_EC_HOST_CMD_BACKEND_UART=y
#CONFIG_UART_ASYNC_API=y
