# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

CONFIG_BOARD_HELIPILOT=y

# System Controller drivers
CONFIG_SYSCON=y

# Hwinfo (used by cros-system driver)
CONFIG_HWINFO=y

# NPCX Flash driver options
CONFIG_PLATFORM_EC_USE_ZEPHYR_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_JESD216_API=y

# NPCX entropy driver options
CONFIG_ENTROPY_GENERATOR=y

# set security strength to 256b
CONFIG_ENTROPY_NPCX_DRBG_SECURITY_STRENGTH_256B=y

# Watchdog
CONFIG_WATCHDOG=y
CONFIG_PLATFORM_EC_WATCHDOG_PERIOD_MS=10000
CONFIG_PLATFORM_EC_WATCHDOG_WARNING_LEADING_TIME_MS=3000

# Console Defines
CONFIG_SHELL_BACKEND_SERIAL=y

# Host Commands
CONFIG_EC_HOST_CMD_INITIALIZE_AT_BOOT=n
CONFIG_EC_HOST_CMD_HANDLER_TX_BUFFER_SIZE=549
CONFIG_EC_HOST_CMD_HANDLER_RX_BUFFER_SIZE=544
CONFIG_EC_HOST_CMD_BACKEND_SHI=y
CONFIG_EC_HOST_CMD_BACKEND_UART=n
CONFIG_UART_ASYNC_API=n

# Enable NPCX firmware header
CONFIG_NPCX_HEADER=y
CONFIG_NPCX_IMAGE_OUTPUT_HEX=y
CONFIG_NPCX_HEADER_SPI_MAX_CLOCK_50=y
CONFIG_NPCX_HEADER_SPI_READ_MODE_DUAL=y
