# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# To build using this configuration simply run:
# $ zmake configure --conf-file zephyr/projects/volteer/volteer/chre.conf \
#       zephyr/projects/volteer/volteer

CONFIG_CHRE=y
CONFIG_STD_CPP11=y
