
ITERABLE_SECTION_RAM(state_cache_uint8_t_val, 1)
ITERABLE_SECTION_RAM(state_cache_uint16_t_val, 2)
ITERABLE_SECTION_RAM(state_cache_uint32_t_val, 4)
ITERABLE_SECTION_RAM(state_cache_uint64_t_val, 8)

ITERABLE_SECTION_RAM(state_cache_uint8_t_ptr_val, 4)
ITERABLE_SECTION_RAM(state_cache_uint16_t_ptr_val, 4)
ITERABLE_SECTION_RAM(state_cache_uint32_t_ptr_val, 4)
ITERABLE_SECTION_RAM(state_cache_uint64_t_ptr_val, 4)
